### ISSUE TITLE
Not able to publish the result to Default site of tableau server (2019.3)

### ISSUE THREAD

**Issue by vmwl** [tableau/Logshark#101]
I am trying to publish the default site but it is failed and said it is 403 unauthorized error.  However, if I publish to other sites (other than default site), it works great.

**Comment by Xantrul** [comment]
What value did you use for `TableauSever:Site` value? For default site it should be blank like this:
`"Site": "",`

**Comment by vmwl** [comment]
Thanks, it works for default if it is blank!  The issue is resolved.

Victor Lee
Technology Services & Operations
Information Technology Group

[cid:image003.png@01D5753E.C5551F90]

Capital Group
(949) 975-6509  DIRECT
(714) 270-0110  MOBILE
6455 Irvine Center Dr, Irvine, CA  92618
victor_m_lee@capgroup.com<mailto:victor_m_lee@capgroup.com> | capitalgroup.com<https://www.capitalgroup.com/>
