### ISSUE TITLE
Publish to server is failing

### ISSUE THREAD

**Issue by bheem123** [tableau/Logshark#102]
Here is the error message:

      -----Published workbooks-----
      Used Standard Reports site on XXXXXX
      Link to the published project: N/A
      Publisher failed to connect to the Tableau Server or create project for th
e results. Exception message: Unexpected occurred while sending request. Excepti
on type: `ex`. Exception message: `Invalid URI: The format of the URI could not
be determined.`

**Comment by Xantrul** [comment]
`Standard Reports` is the display name of the site, but Tableau REST API expects "content url" of the site - it is what you see in the URL when accessing the browser. I.e. `thisisyoursitename` in https://awesome-server.tableau.com/#/site/thisisyoursitename/home

If using content url for "Site" doesn't resolve the issue, plz double-check Tableau Sever URL provided. Make sure it included `https://` part

**Comment by Xantrul** [comment]
Closing this one. If the issue persists - please let us know.
