### ISSUE TITLE
Write to Postgres database is not working

### ISSUE THREAD

**Issue by bheem123** [tableau/Logshark#103]
Here is the error:

     -----Summary-----
      Run ID 19112712352936-11272019 failed after running for 00:00:00.7333460.
Reported problem: Exception occurred while initializing writer factory for write
r 'postgres'. Exception message: One or more errors occurred. (No such host is k
nown)
      Information below might contain more details on what exactly failed

      -----Processing errors-----
      No errors occurred while processing log set

Here is the command I used:

LogShark D:\TableauZiplogs\Ziplogs_20191127.zip 11272019 -p -w postgres

**Comment by Xantrul** [comment]
`No such host is known` is the real error here. This most likely mean that LogShark cannot resolve host name of the database (specified in `PostgresWriterDatabase` with either `ConnectionString` or `Host` options). 

Please take a look at https://tableau.github.io/Logshark/docs/logshark_postgres for different options to tell LogShark database information. Also it is worth checking that machine running LogShark can resolve host name of the database server (i.e. simply ping it from command line)

**Comment by bheem123** [comment]
Yes, the error seems obvious, but I was able to ping the host where Postgres database is located.
Should I try with IP?

Thanks
-Bheem

**Comment by Xantrul** [comment]
Yeah, IP should work as well as host name. If it doesn't work, try to provide hostname through command line parameter `--pg-db-host` instead. Providing hostname this way overrides value in config

**Comment by Xantrul** [comment]
Closing this one. If the issue persists - please let us know.
