### ISSUE TITLE
Error running Logshark 4.1

### ISSUE THREAD

**Issue by Jeganvignesh** [tableau/Logshark#104]
I get an error when I try to run Logshark

D:\>Logshark D:\tabserverlogs.zip
Loading Logshark user configuration..
Failed to initialize Logshark request processor!
Please check to make sure that the results database was configured correctly. (F
ailed to open connection to localhost:5432: 28000: no pg_hba.conf entry for host
 "::1", user "logshark", database "postgres", SSL off)

**Comment by Xantrul** [comment]
Each PostgreSQL database has `pg_hba.conf` file which describes who can connect to what database, from which IP addresses and how they should authenticate. The error message means none of the records in `pg_hba.conf` allow to connect user "logshark" to database "postgres" from the "::1" address (IPv6 localhost).

The easiest solution is to add a record to the `pg_hba.conf` file allowing "logshark" to connect from this IP using username and password. Then restart PostgreSQL.

Here's the link to Postgres documentation re this file: https://www.postgresql.org/docs/current/auth-pg-hba-conf.html

**Comment by Xantrul** [comment]
Closing this one. If the issue persists - please let us know.
