### ISSUE TITLE
 After parsing a value an unexpected character was encountered: t. Path 'sess', line 1, position 112

### ISSUE THREAD

**Issue by kish2590** [tableau/Logshark#105]
I have connected to logshark and able to download the dashboards using log files.
Later we  have upgraded tableau server to 2019.3, then after i am unable to get the dashboards.

i am getting the below error .
 "After parsing a value an unexpected character was encountered: t. Path 'sess', line 1, position 112"
 for backgrounder file

**Comment by Xantrul** [comment]
Hi,

We see this warning a lot - when backgrounder was shut down for whatever reason it sometimes starts to write logs on the same line it stopped before ending up with incorrect JSON in that one line. 

LogShark 4.1 expected to simply skip this one line, report a "processing error" and then continue processing the rest of the life. So if you see this message under "Processing errors" section of the run summary - there is nothing to worry about: LogShark simply skipped processing one incorrect line in the logs and nothing else is affected.

If you see this error message somewhere else though - please lmk
