### ISSUE TITLE
Cache Servers missing from Config workbook

### ISSUE THREAD

**Issue by tonykau1** [tableau/Logshark#106]
Hi Team,
Curious if this is omitted on purpose or an oversight, but the redis cache server processes aren't showing up on the config workbook.  They're listed under cacheserver.hosts on the Full Config dashboard so it's not too hard to find, but would be great if they were added to that visual "green checkmark" data source/dashboard as well.

Much appreciated!
-Tony

**Comment by Xantrul** [comment]
Hi Tony,
Good catch! It looks like cacheserver configured in a slightly different way than other processes and that's why our current parsing code doesn't catch it as a valid process. We will need to add a special case in the code this cacheserver.

@bermetj

**Comment by bermetj** [comment]
@tonykau1, thank you for submitting this issue. We have added your request to our backlog.

**Comment by Pendulin** [comment]
This has been resolved, and the latest version of LogShark should pull redis cache server process information from the logs.
