### ISSUE TITLE
Getting "command not found" error while trying to run LogShark on mac

### ISSUE THREAD

**Issue by RajMani11** [tableau/Logshark#107]
I followed the instructions and unzipped the LogShark for mac file. Then i went inside the unzipped folder and tried to issue "LogShark --help" command and it says "command not found".

**Comment by mstromb** [comment]
If the current directory is not in your `PATH` you'll need to prefix the command with `./`, eg `./LogShark --help`

**Comment by RajMani11** [comment]
Thank you. It works with "./" prefix as long as i run the commands from inside the LogShark folder.

**Comment by z333d** [comment]
suppose the path of logshark is /path/to/logshark, you can add it to PATH and export it, add the following line into your shell config file, like .bashrc or .zshrc:
`
export PATH="$HOME/Applications/LogShark.Mac.4.2:$PATH"
`
then source it.
go to /path/to/logshark, make LogShark executable,
`
chmod +x LogShark
`

then, you can run LogShark at any place
