### ISSUE TITLE
replaycreation plugin missing

### ISSUE THREAD

**Issue by lueksche** [tableau/Logshark#108]
Hi all,

following the instruction on replayer, I want to extract the traffic form the ziplogs. The guide tells me to use the  --plugins ReplayCreation. When running logshark it fails "Did not find any plugins matching name(s) provided".
Was the plugin removed in the latest version or do I have to 'activate' the plugin?

https://community.tableau.com/docs/DOC-11062?_ga=2.50991021.584755936.1578296093-245455482.1570712957

**Comment by Xantrul** [comment]
Hi,
LogShark 4.1 release doesn't have Replayer plugin. It was added later however, so the next release we do here should include it.

In the meantime, please use LogShark 3.0.2 to generate Replayer data.

**Comment by lueksche** [comment]
Hi,
thank you for your fast response.

**Comment by Pendulin** [comment]
The Replayer plugin has been added. It's disabled by default, but can be run by specifying it in the command line parameters, or by altering the set of default plugins in the configuration file.
