### ISSUE TITLE
Update URL for Tableau Commands on https://tableau.github.io/Logshark/docs/logshark_run

### ISSUE THREAD

**Issue by hemingsent** [tableau/Logshark#109]
When you click the link to view the Tableau Commands below examples it goes to a 404.

Link it is trying to go to: https://tableau.github.io/Logshark/docs/LogShark_cmds
Link it should go to :https://tableau.github.io/Logshark/docs/logshark_cmds

![image](https://user-images.githubusercontent.com/8901946/72096097-60fbfc00-32ce-11ea-844e-cd158b3564fd.png)

**Comment by bermetj** [comment]
@hemingsent, thanks for letting us know! We'll update it.
