### ISSUE TITLE
fatal error while processing logset:

### ISSUE THREAD

**Issue by blicalzi** [tableau/Logshark#11]
I have tried several iterations of execute logshark against a "tabadmin ziplogs -d MM/DD/YYYY" output - even when I minimize the number of days to output the log for, I seem to always end up receiving an error while processing a logset (near its final stages of processing) - with the error in Logshark.log showing:

[1] DEBUG Logshark.CLI.LogsharkCLI - Logshark.Exceptions.InvalidLogsetException: Target does not appear to be a valid Tableau logset!

**Comment by jmangue** [comment]
Hi blicalzi,

That error generally indicates that Logshark is not recognizing your zip archive as a Tableau Server logset.

There are two things Logshark looks for to determine whether a zip is a Server logset --

1. Presence of a "buildversion.txt" file in the root of the zip
2. Presence of a "workgroup.yml" file in the "config" folder inside the zip

If either of those files are missing, try taking another ziplogs and see if that fixes the issue.  Let us know how it goes!

**Comment by blicalzi** [comment]
Hi jmangue,
Thank you for the info - it appears the problem is #2 that you mentioned, I do not see a workgroup.yml file inside the config folder.

A couple observation worth noting:

- I was using the :>tabadmin ziplogs command, but outputting to a UNC path.  The file would output, but there would be 'unexpected error during zip' messages in the tabadmin command echo.

- The resulting ziplogs to the UNC path would not contain the files you mention (as well as the tabsvc.yml file within the root of the zip.

- using tabadmin ziplog command with 'stdout' or to a non-UNC path appears to work fine, no errors.  And thus, :> logshark {logfile} -p  works perfect - even if I move the logfile to a UNC location, and refer the logshark command to the UNC location of the logfile.

So it appears there is just incompatibility nested somewhere deep in the tabadmin ziplog command when referencing UNC paths.
Thank you very much for your help jmangue!
