### ISSUE TITLE
To identify reason behind a slowly loading viz

### ISSUE THREAD

**Issue by arunyadav19** [tableau/Logshark#111]
Hi Team,

If I want to understand which particular component or filter or query in my workbook caused the slowness or took longer time , where can I see this information in the workbooks generated by logshark ?

I remember seeing a screenshot which was indicating that a high cardinality filter was causing slowness in the workbook. I'm looking for similar kind of workbook using which I can approach my users to work on those pain points.

Thanks in advance !!

**Comment by Xantrul** [comment]
Hi,
It sounds like ART plugin and workbook would be the best choice for this investigation. It shows the detailed data about how much CPU/memory/time each step took while rendering the view.

We also have very detailed documentation for this workbook written by one of our experts in performance investigations: https://tableau.github.io/Logshark/docs/logshark_art
