### ISSUE TITLE
CPU doesn't have necessary features to run this build

### ISSUE THREAD

**Issue by 2xCmet** [tableau/Logshark#115]
Hi,

first of all, I love your Product it works fantastically while I'm using it on my Laptop with a Intel i5 6300U and 16 GB of RAM.
I'm currently trying to automate our Deployment Process of the LogShark Workbooks and Data Source, but unfortunately I'm not able to get LogShark running on our External Server.

All Requirements which are listed under the following Link are fullfilled:
https://tableau.github.io/Logshark/docs/logshark_prefunc
We are running Windows 2012 R2 with a Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, 2300 Mhz, 8 Core(s), 8 Logical Processor(s) and 128 GB of RAM.

When I try to start LogShark it fails with the following Error Message:

2020-04-16T09:37:16.6946127+02:00  [INF] Hyper Writer requested. Initializing writer factory... (eaf4f6e1)
2020-04-16T09:37:16.8068892+02:00  [ERR] Exception occurred while initializing writer factory for writer 'hyper'. Exception message: Failed to start a new Hyper instance.
Context: 0x86a93465
 (4b8fcd72)
Tableau.HyperAPI.HyperException: Failed to start a new Hyper instance.
Context: 0x86a93465
 ---> Tableau.HyperAPI.HyperException: The Hyper server process exited during startup with exit code: 1, Command-line: ""C:\Users\U549949s\Documents\Performance Workbooks Script\LogShark.Win.4.1.1911.09672-public\hyperdstarter.exe" -x "fallback_on_unknown_locale=en_US" -x "hyper_temp_directory_override=C:\Users\U549949s\AppData\Local\Temp\6\LogShark" -x "log_config=file,json,all,hyperd,0" --database "hyper_db_RQdP9SUI" --init "overwrite" --init-user "tableau_internal_user" --log-dir "Logs" --no-password --no-ssl --skip-license --listen-connection "tab.pipe://./pipe/auto" --callback-connection "tab.pipe://./pipe/{4E5E39F1-1822-4533-AA3B-80C210D1A69E}" run"
Context: 0x13cead20
   --- End of inner exception stack trace ---
   at Tableau.HyperAPI.Raw.Error.Check(IntPtr errp)
   at Tableau.HyperAPI.HyperProcess..ctor(String hyperPath, Telemetry telemetry, String userAgent, Dictionary`2 parameters)
   at LogShark.Writers.Hyper.HyperWriterFactory..ctor(String outputDirectory, String runId, String appendToRunId, String hyperLocation, String hyperLogDir, String hyperTempDir, String workbookTemplatesDirectory, String customWorkbookTemplatesDirectory, String customWorkbookSuffix, ILoggerFactory loggerFactory) in /Users/eorlianskii/RiderProjects/logshark/LogShark/Writers/Hyper/HyperWriterFactory.cs:line 45
   at LogShark.LogSharkRunner.GetWriterFactory(String runId) in /Users/eorlianskii/RiderProjects/logshark/LogShark/LogSharkRunner.cs:line 236
   at LogShark.LogSharkRunner.ProcessLog() in /Users/eorlianskii/RiderProjects/logshark/LogShark/LogSharkRunner.cs:line 138

I tried running the command as Administrator and it still doesn't work.
When looking at the hyperd.logs I find these Information:

{"ts":"2020-04-16T10:37:23.211","pid":3544,"tid":"236c","sev":"info","req":"-","sess":"-","k":"fault-reporting-init","v":{"log-path":"\\\\?\\C:\\Users\\U549949s\\Documents\\Tableau Logshark\\Logs\\hyperd-error_3544_20-0416-103723.log"}}
{"ts":"2020-04-16T10:37:23.216","pid":3544,"tid":"236c","sev":"info","req":"-","sess":"-","k":"startup-info","v":{"command-line":"E:\\\\Applications\\\\LogShark.Win.4.1.2\\\\hyperd.exe -x date_style=MDY -x hyper_temp_directory_override=Temp -x language=en_US -x log_config=file,json,all,hyperd,0 --database=C:\\\\Users\\\\U549949s\\\\AppData\\\\Local\\\\Temp\\\\hyper_db_Kr7TSGkS --init=overwrite --init-user=tableau_internal_user --log-dir=Logs --no-password --skip-license --listen-connection tab.pipe://./pipe/auto --callback-connection tab.pipe://./pipe/{86295A2A-4BDF-4215-B1D7-0F5C8C4FFB8F} run","server-version":"9.1.0","build-version":"hyperapi_release_4.0.0.0.9746.rc378815c","build-type":"Release","build-cpu-features":["sse2","sse4.2"],"network-threads":8,"parent-pid":4772,"min-protocol-version":1,"max-protocol-version":1,"temp-directory":"\\\\?\\C:\\Users\\U549949s\\Documents\\Tableau Logshark\\Temp"}}
{"ts":"2020-04-16T10:37:23.216","pid":3544,"tid":"236c","sev":"info","req":"-","sess":"-","k":"startup-settings","v":{"settings":{"Hyper.Mode.Experimental": "", "Hyper.Mode.Standard": "", "Tableau.LogLevel.Debug": "", "Tableau.LogLevel.Error": "", "Tableau.LogLevel.Fatal": "", "Tableau.LogLevel.Info": "", "Tableau.LogLevel.Off": "", "Tableau.LogLevel.Trace": "", "Tableau.LogLevel.Warn": "", "adaptive_compilation": true, "case_contains_optimization_mode": "3", "client_slow_phase_threshold": "100ms", "client_slow_threshold": "200ms", "compilation_slow_threshold": "200ms", "crash_dump_path": "\"\"", "database_canonicalize_paths": true, "database_directory": "", "database_directory_implementation": "localfile", "database_directory_mapping_rules": "[]", "database_path_canonicalization_threshold": "100ms", "date_style": "MDY", "dbcache_directory": "\"\"", "dbcache_disk_limit": "0", "dbcache_entry_lifetime": "10080min", "dbcache_entry_limit": -1, "deduplicate_query_fragments": true, "default_database_version": "0", "enable_scheduler_task_preemption_cancellation": false, "extra_float_digits": 0, "fallback_on_unknown_locale": "", "file_partition_size_limit": "0", "force_shadow_objectstore": false, "global_file_partition_size_limit": "0", "hard_concurrent_query_thread_limit": "150%", "hyper_temp_directory_override": "\"Temp\"", "lambda_restriction_only_if_unreusable": true, "language": "en_US", "llvm_compilation_cpu_features": "-avx512ifma,-avx512dq,-avx512er,-avx512vpopcntdq,-avx512vl,-avx512cd,-avx512f,-avx512bw,-avx512vbmi,-avx512pf", "log_adaptive_optimization": false, "log_block_partition": false, "log_bulk_insert": false, "log_bump_allocator": false, "log_code_metrics": false, "log_collation_mismatch": true, "log_common_subexpression_extraction": false, "log_common_subexpression_hoisting": false, "log_config": "file,json,all,hyperd,0", "log_connection": false, "log_constraint_check": false, "log_continuations": false, "log_copy_external_stream": false, "log_database": false, "log_expression_reuse": false, "log_external_streams": false, "log_external_table_cache": false, "log_file_backup_size_limit": "0", "log_file_max_count": 0, "log_file_path": "\"\\\\?\\C:\\Users\\U549949s\\Documents\\Tableau Logshark\\Logs\"", "log_file_size_limit": "0", "log_filter_join": false, "log_hashtable_sizes": false, "log_join_plan": false, "log_memory_tracker": false, "log_memory_tracker_threshold": "16777215t", "log_objectstore": false, "log_optimizer_statistics": false, "log_optimizersteps": false, "log_pipeline_dependencies": false, "log_pipelines": false, "log_plan_cache": false, "log_queries": true, "log_query_cpu": true, "log_query_graph": false, "log_query_plans": false, "log_resource_usage_interval": "10s", "log_resource_usage_mode": "19", "log_sample": false, "log_scheduler": false, "log_scheduler_condvar": false, "log_schema_serialization": false, "log_script_pipelines": false, "log_service_name": "hyperd", "log_spooling_fallback_verbose": false, "log_stack_on_error": false, "log_statement_latches": false, "log_timing": false, "log_translation_mapping_choice": false, "log_troublesome_query_plans": true, "log_unflushedmemory": false, "log_writebuffer": false, "max_query_size": "64m", "memory_limit": "80%", "memtracker_hard_reclaim_threshold": "80%", "memtracker_soft_reclaim_threshold": "50%", "metric_additional_headers": "", "metric_additional_payload": "", "metric_certificate_path": "", "metric_publish_interval": "0s", "metric_server_host": "", "metric_server_path": "", "metric_server_port": 443, "metric_skip_verify_peer": false, "metric_use_gzip": false, "metrics_memory_limit": "50m", "named_pipes_allow_all_users": false, "network_threads": "100%", "objectstore_backing_resource_slow_threshold": "200ms", "objectstore_validate_checksums": false, "open_files_ulimit": 0, "optimize_extract_year": true, "optimize_hoist_contains_from_map": true, "optimize_lambda_restriction": true, "optimize_searched_case_const_lookup": true, "optimize_tde_lambda_restriction": true, "password_encryption": "md5", "query_settings": "", "query_total_time_limit": "0s", "request_database_threshold": "500ms", "restrict_database_directory": true, "sample_cluster_block_factor": 0.1, "sample_cluster_block_factor_threshold": 0.001, "sample_max_tuples": 100000000, "sample_max_tuples_persisted": 1000, "sample_min_tuples": 1000, "sample_size_factor": 0.005, "scheduler_load_include_queue_length": false, "scheduler_task_preemption_cancellation_threshold": "120min", "scheduler_task_preemption_cancellation_threshold25": "30min", "scheduler_task_preemption_cancellation_threshold50": "5min", "scheduler_task_preemption_frequency": "1s", "session_memory_limit": "16777215t", "short_circuiting": true, "single_file_storage_implementation": "mmap", "soft_concurrent_query_thread_limit": "100%", "srm_cpu_limit_use_average": true, "srm_detailed_logging": false, "srm_logging_multiple": 900, "storage_providers": "", "string_pool_file_allocation": "16m", "tde_scan_once_default": false, "telemetry_production_mode": true, "telemetry_wait_last_event": "1s", "temp_disk_space_limit": "100%", "transitive_join_condition_optimization_limit": 7, "troublesome_query_execution_threshold": "10s", "two_digit_year_threshold": 70, "use_containsany": true, "use_new_join_estimates": true, "use_spooling_fallback": true, "watchdog_timeout": "5min", "writebuffer_max_size_per_thread": "0", "writebuffer_min_size_per_query": "0"}}}
{"ts":"2020-04-16T10:37:23.216","pid":3544,"tid":"236c","sev":"fatal","req":"-","sess":"-","k":"incompatible-cpu","v":{"msg":"CPU doesn't have necessary features to run this build"}}
{"ts":"2020-04-16T10:37:23.217","pid":3544,"tid":"236c","sev":"info","req":"-","sess":"-","k":"logging-end","v":{}}

Is there a way that LogShark to minimze the LogShark or the hyperd Requirements so that it can start a Writer Instance even with a CPU which is now nearly 6 years old?

With best Regards
Christian Seifert

Attached you will find the complete Logs.
[LogShark-20200416.log](https://github.com/tableau/Logshark/files/4485903/LogShark-20200416.log)
[hyperd.log](https://github.com/tableau/Logshark/files/4485904/hyperd.log)

**Comment by Xantrul** [comment]
Hi Christian,

Are trying to run LogShark directly on the machine, or inside a VM? The only time I saw this error message before was when someone tried to run LogShark on a Hyper-V VM and enabled "simplified CPU instruction set" feature.

**Comment by 2xCmet** [comment]
Hi Xantrul,

thank you for your Fast reply. 

When I checked the System Information of this Server I found the following:
System Manufacturer	Microsoft Corporation
System Model	Virtual Machine
System Type	x64-based PC
System SKU	Unsupported

So you are right it seems like that we are indeed using a VM here. As I'm not the System Owner I'm not able to check if simplified CPU instruction set is enabled or not. Or is there a way to check if this Option is enabled without restarting the Server? 

If this Setting is enabled is there a way to get LogShark running?

**Comment by Xantrul** [comment]
If Hyper says that it cannot run on this CPU - there is nothing can we do to force it to run on this machine. You can use LogShark without Hyper though: we have an ability to [output results into PostgreSQL database](https://tableau.github.io/Logshark/docs/logshark_postgres) and in this case Hyper writer is not used at all.

As for diagnosing a particular virtual machine in question, I am probably not the best person to help: my team is using publicly-available Hyper API NuGet package, but we don't have much details on how it works under the hood. That being said, as the first step I would check what CPU instruction sets are available on the machine. Looks like Microsoft recommends [coreinfo](https://docs.microsoft.com/en-us/sysinternals/downloads/coreinfo) tool. At the very least I would expect CPU to support `SSE4.2` set. If it is missing, most likely virtual CPU is very limited.

**Comment by 2xCmet** [comment]
Ok, that is unfortunate to hear. Do you know if there is any Performance Difference between using Hyper directly and using a Postgre SQL Database?

I've just run coreinfo and if I'm understanding the Output correctly SSE4.2 is enabled. But could you take a look as well?
[output.txt](https://github.com/tableau/Logshark/files/4508343/output.txt)

**Comment by 2xCmet** [comment]
Thank you for your answer. As changing the configuration would cost us Money, this is not an option. Therefore we will have to take the PostgreSQL Database instead of the Hyper File and extract it on the Tableau Server directly.

Again thank you very much for your help.
