### ISSUE TITLE
Logshark signin Error is persistent

### ISSUE THREAD

**Issue by avnikhil22** [tableau/Logshark#117]
I followed every part as mentioned in  the documentation but I ran into this error. We want to resolve the stability issue of our server at the earliest and I know logshark is the only way.
Please advise on the following:

      Initializing TableauServerRestApi for site `Internal` on `https://tableaud
ev.wfscorp.com`
fail: LogShark.Writers.WorkbookPublisher[0]
      Exception encountered when attempting to sign in or create the project: Ht
tp error returned while sending a request. Error reported: Call failed with stat
us code 401 (Unauthorized): POST https://tableaudev.wfscorp.com/api/2.8/auth/sig
nin. Response body {"error":{"summary":"Signin Error","detail":"Error signing in
 to Tableau Server","code":"401001"}}
fail: LogShark.LogSharkRunner[0]
      Workbook publisher failed to connect to the Tableau Server or create proje
ct for the results. Exception message: Http error returned while sending a reque
st. Error reported: Call failed with status code 401 (Unauthorized): POST https:
//tableaudev.wfscorp.com/api/2.8/auth/signin. Response body {"error":{"summary":
"Signin Error","detail":"Error signing in to Tableau Server","code":"401001"}}
info: LogShark.Program[0]

      -----Summary-----
      Run ID 20042200582248-egw-wap-d78-ziplogs failed after running for 00:00:3
3.4344052. Reported problem: Workbook publisher failed to connect to the Tableau
 Server or create project for the results. Exception message: Http error returne
d while sending a request. Error reported: Call failed with status code 401 (Una
uthorized): POST https://tableaudev.wfscorp.com/api/2.8/auth/signin. Response bo
dy {"error":{"summary":"Signin Error","detail":"Error signing in to Tableau Serv
er","code":"401001"}}
      This problem is unexpected and it is not known whether or not it will go a
way if LogShark is run again.
      Information below might contain more details on what exactly failed

      -----Processing errors-----
      1 errors occurred while processing log set:
      Details of all reported errors:
      --> File: `node1/searchserver_0.20192.19.0718.1543893510372821996264/logs/
searchserver-0.log`. Line: 7367. Reported by: `SearchServerPlugin`. Error: `Fail
ed to parse log line as SearchServer event`

      -----Published workbooks-----
      Used Internal site on https://tableaudev.wfscorp.com
      Link to the published project: N/A
      Publisher failed to connect to the Tableau Server or create project for th
e results. Exception message: Http error returned while sending a request. Error
 reported: Call failed with status code 401 (Unauthorized): POST https://tableau
dev.wfscorp.com/api/2.8/auth/signin. Response body {"error":{"summary":"Signin E
rror","detail":"Error signing in to Tableau Server","code":"401001"}}

      -----Generated workbooks-----
      Workbook templates available: Apache; Art; Backgrounder; ClusterController
; Config; Filestore; Hyper; Netstat; Postgres; ResourceManager; SearchServer; Se
rverTelemetry; Tabadmin; Vizportal; VizqlDesktop
      Successfully generated workbooks with data: Apache; Art; Backgrounder; Clu
sterController; Config; Filestore; Hyper; Netstat; Postgres; ResourceManager; Se
archServer; ServerTelemetry; Vizportal
      Empty workbooks: Tabadmin; VizqlDesktop

      -----Log Reading Statistics-----
      Processed zip file compressed size: 60 MB
      Additional tags returned by plugins: '2019.2.2';'20192.19.0718.1543'
      Plugins that received any data: Apache, Art, Backgrounder, ClusterControll
er, Config, Filestore, Hyper, Netstat, Postgres, ResourceManager, SearchServer,
ServerTelemetry, Vizportal

**Comment by Xantrul** [comment]
Hi Nikhil,

The meaning of error code 401001 from documentation: `The credentials (name or password, or personal access token name or secret) are invalid for the specified site, or the site content URL is invalid.`

I think in this case you're hitting the last part `...or the site content URL is invalid.` because site name in the Summary starts with capital letter (`Internal`). Each Tableau Server site had 2 "names": user-friendly name creator gave it and "content URL" generated from the original name to use in URLs. Tableau Server REST API sign in requires the latter. To find out what is the content URL for this site, simply log into Tableau Server, navigate to that site and look at the current URL in the browser.

**Comment by avnikhil22** [comment]
Hi Xantrul,
Thank you for the response, I did the required changes and this time I face another error mentioned below 

      Initializing TableauServerRestApi for site `External` on `https://tableaud
ev.wfscorp.com/#/site/External/home`
fail: LogShark.Writers.WorkbookPublisher[0]
      Exception encountered when attempting to sign in or create the project: Ht
tp error returned while sending a request. Error reported: Call failed with stat
us code 400 (Bad Request): POST https://tableaudev.wfscorp.com/auth/signin#/site
/External/home/api/2.8. Response body <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2
.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

fail: LogShark.LogSharkRunner[0]
      Workbook publisher failed to connect to the Tableau Server or create proje
ct for the results. Exception message: Http error returned while sending a reque
st. Error reported: Call failed with status code 400 (Bad Request): POST https:/
/tableaudev.wfscorp.com/auth/signin#/site/External/home/api/2.8. Response body <
!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

info: LogShark.Program[0]

      -----Summary-----
      Run ID 20042312513231-egw-wap-d78-ziplogs failed after running for 00:00:4
6.2038266. Reported problem: Workbook publisher failed to connect to the Tableau
 Server or create project for the results. Exception message: Http error returne
d while sending a request. Error reported: Call failed with status code 400 (Bad
 Request): POST https://tableaudev.wfscorp.com/auth/signin#/site/External/home/a
pi/2.8. Response body <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

      This problem is unexpected and it is not known whether or not it will go a
way if LogShark is run again.
      Information below might contain more details on what exactly failed

      -----Processing errors-----
      1 errors occurred while processing log set:
      Details of all reported errors:
      --> File: `node1/searchserver_0.20192.19.0718.1543893510372821996264/logs/
searchserver-0.log`. Line: 7367. Reported by: `SearchServerPlugin`. Error: `Fail
ed to parse log line as SearchServer event`


      -----Published workbooks-----
      Used External site on https://tableaudev.wfscorp.com/#/site/External/home
      Link to the published project: N/A
      Publisher failed to connect to the Tableau Server or create project for th
e results. Exception message: Http error returned while sending a request. Error
 reported: Call failed with status code 400 (Bad Request): POST https://tableaud
ev.wfscorp.com/auth/signin#/site/External/home/api/2.8. Response body <!DOCTYPE
HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

**Comment by Xantrul** [comment]
Hi Nikhil,

From what I see in the report you posted, the correct configuration for this server/site would be:
* Url: `https://tableaudev.wfscorp.com`
* Site: `External`

Please try this. If it doesn't work and throws `401001` code again, then double-check the `Site` parameter (i.e. it could be `external` with lower-case `e`)

**Comment by avnikhil22** [comment]
Thanks Xantrul its working now. 
Github community is awesome. Love you all.

**Comment by avnikhil22** [comment]
I hate to reopen this again. Everything is working fine except the ART and backgrounder workbooks are not populating. Please see the error.
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-14`. Line: 2564. Reported by: `BackgrounderPlu
gin`. Error: `Failed to process string as Backgrounder event. This is expected f
or logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-15`. Line: 3458. Reported by: `BackgrounderPlu
gin`. Error: `Failed to process string as Backgrounder event. This is expected f
or logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-15`. Line: 3459. Reported by: `BackgrounderPlu
gin`. Error: `Failed to process string as Backgrounder event. This is expected f
or logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-20`. Line: 1103. Reported by: `BackgrounderPlu
gin`. Error: `Failed to process string as Backgrounder event. This is expected f
or logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-22`. Line: 382. Reported by: `BackgrounderPlug
in`. Error: `Failed to process string as Backgrounder event. This is expected fo
r logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-22`. Line: 383. Reported by: `BackgrounderPlug
in`. Error: `Failed to process string as Backgrounder event. This is expected fo
r logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-22`. Line: 384. Reported by: `BackgrounderPlug
in`. Error: `Failed to process string as Backgrounder event. This is expected fo
r logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-22`. Line: 385. Reported by: `BackgrounderPlug
in`. Error: `Failed to process string as Backgrounder event. This is expected fo
r logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-0.log.2020-04-22`. Line: 386. Reported by: `BackgrounderPlug
in`. Error: `Failed to process string as Backgrounder event. This is expected fo
r logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-1.log.2020-04-10`. Line: 5436. Reported by: `BackgrounderPlu
gin`. Error: `Failed to process string as Backgrounder event. This is expected f
or logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-1.log.2020-04-10`. Line: 5439. Reported by: `BackgrounderPlu
gin`. Error: `Failed to process string as Backgrounder event. This is expected f
or logs prior to 10.4`
      --> File: `node2/backgrounder_0.20183.18.1214.08082592108881669546082/logs
/backgrounder_node2-1.log.2020-04-10`. Line: 5440. Reported by: `BackgrounderPlu
gin`. Error: `Failed to process string as Backgrounder event. This is expected f
or logs prior to 10.4`


      -----Published workbooks-----
      Used External site on https://tableaudev.wfscorp.com
      Link to the published project: https://tableaudev.wfscorp.com#/site/Extern
al/projects?search=20042409250033-egw-wap-d78-05776245-logs
      Successfully published workbooks: Apache; Art [No Data]; Backgrounder; Clu
sterController; Config; Filestore; Hyper; Netstat; Postgres; ResourceManager; Se
archServer; ServerTelemetry [No Data]; Tabadmin [No Data]; Vizportal; VizqlDeskt
op [No Data]

      -----Generated workbooks-----
      Workbook templates available: Apache; Art; Backgrounder; ClusterController
; Config; Filestore; Hyper; Netstat; Postgres; ResourceManager; SearchServer; Se
rverTelemetry; Tabadmin; Vizportal; VizqlDesktop
      Successfully generated workbooks with data: Apache; Backgrounder; ClusterC
ontroller; Config; Filestore; Hyper; Netstat; Postgres; ResourceManager; SearchS
erver; Vizportal
      Empty workbooks: Art; ServerTelemetry; Tabadmin; VizqlDesktop

      -----Log Reading Statistics-----
      Processed zip file compressed size: 1,247 MB
      Additional tags returned by plugins: '2018.3.2';'20183.18.1214.0808'
      Plugins that received any data: Apache, Art, Backgrounder, ClusterControll
er, Config, Filestore, Hyper, Netstat, Postgres, ResourceManager, SearchServer,
ServerTelemetry, Vizportal

      Apache                                            : Processed 14 files in
00:02:19.2404941. Elapsed: 00:02:19.2404941. Total size: 1063 MB. Processing at
7.63 MB/sec
      BackgrounderCpp                                   : Processed 119 files in
 00:00:09.5038320. Elapsed: 00:00:09.5038320. Total size: 246 MB. Processing at
25.88 MB/sec
      BackgrounderJava                                  : Processed 118 files in
 00:00:07.3690508. Elapsed: 00:00:07.3690508. Total size: 82 MB. Processing at 1
1.13 MB/sec
      ClusterController                                 : Processed 16 files in
00:00:00.0225021. Elapsed: 00:00:00.0225021. Total size: 0 MB. Processing at 0.0
0 MB/sec
      DataserverCpp                                     : Processed 30 files in
00:00:04.3949794. Elapsed: 00:00:04.3949794. Total size: 121 MB. Processing at 2
7.53 MB/sec
      Filestore                                         : Processed 15 files in
00:00:00.0407796. Elapsed: 00:00:00.0407796. Total size: 0 MB. Processing at 0.0
0 MB/sec
      Hyper                                             : Processed 88 files in
00:18:11.8962514. Elapsed: 00:18:11.8962514. Total size: 14679 MB. Processing at
 13.44 MB/sec
      NetstatWindows                                    : Processed 2 files in 0
0:00:00.0992504. Elapsed: 00:00:00.0992504. Total size: 0 MB. Processing at 0.00
 MB/sec
      PostgresCsv                                       : Processed 7 files in 0
0:00:01.5587882. Elapsed: 00:00:01.5587882. Total size: 16 MB. Processing at 10.
26 MB/sec
      ProtocolServer                                    : Processed 339 files in
 00:00:10.4566808. Elapsed: 00:00:10.4566808. Total size: 245 MB. Processing at
23.43 MB/sec
      SearchServer                                      : Processed 15 files in
00:00:26.0212786. Elapsed: 00:00:26.0212786. Total size: 483 MB. Processing at 1
8.56 MB/sec
      TabsvcYml                                         : Processed 2 files in 0
0:00:00.5947007. Elapsed: 00:00:00.5947007. Total size: 0 MB. Processing at 0.00
 MB/sec
      VizportalCpp                                      : Processed 15 files in
00:00:00.0926966. Elapsed: 00:00:00.0926966. Total size: 1 MB. Processing at 10.
79 MB/sec
      VizportalJava                                     : Processed 15 files in
00:00:02.8739099. Elapsed: 00:00:02.8739099. Total size: 90 MB. Processing at 31
.32 MB/sec
      VizqlserverCpp                                    : Processed 37 files in
00:00:04.6568137. Elapsed: 00:00:04.6568137. Total size: 112 MB. Processing at 2
4.05 MB/sec
      WorkgroupYml                                      : Processed 2 files in 0
0:00:00.0975120. Elapsed: 00:00:00.0975120. Total size: 0 MB. Processing at 0.00
 MB/sec
      Zookeeper                                         : Processed 15 files in
00:00:15.2645781. Elapsed: 00:00:15.2645781. Total size: 279 MB. Processing at 1
8.28 MB/sec

      -----Data Writers Statistics-----
      Lines persisted per data set:
      Apache_ApacheRequests                             : 4708147 lines persiste
d
      Backgrounder_BackgrounderJobErrors                : 20804 lines persisted
      ClusterController_ClusterControllerErrors         : 21 lines persisted
      ClusterController_ZookeeperErrors                 : 2 lines persisted
      ClusterController_ZookeeperFsyncLatencies         : 14 lines persisted
      Config_ConfigEntries                              : 6219 lines persisted
      Config_ProcessTopology                            : 34 lines persisted
      Filestore_Filestore                               : 383 lines persisted
      Hyper_HyperErrors                                 : 3823 lines persisted
      Hyper_HyperQueries                                : 11600723 lines persist
ed
      Netstat_NetstatEntries                            : 4252 lines persisted
      Postgres_PostgresEvents                           : 15853 lines persisted
      ResourceManager_ResourceManagerActions            : 14 lines persisted
      ResourceManager_ResourceManagerCpuSamples         : 2692 lines persisted
      ResourceManager_ResourceManagerHighCpuUsages      : 30066 lines persisted
      ResourceManager_ResourceManagerMemorySamples      : 2706 lines persisted
      ResourceManager_ResourceManagerThresholds         : 12 lines persisted
      SearchServer_SearchServerEvents                   : 1714667 lines persiste
d
      Vizportal_VizportalEvents                         : 29799 lines persisted

**Comment by Xantrul** [comment]
Hi Nikhil,

For ART plugin - Do you see any processing errors reported by Art plugin? According to this report Art plugin did get log data fed into it, but did not write anything in the output. Most likely it simply did not find any ART records in the logs. ART logging is a fairly new feature and it t looks like you're running Tableau Server 2018.3, so maybe your server doesn't log ART events yet (or there was no related activity in the time frame of the log set)

For Backgrounder - Plugin definitely found some data: `Backgrounder_BackgrounderJobErrors : 20804 lines persisted` That is a lot of errors! Also according to report you've got 119 BackgrounderCpp and 118 BackgrounderJava log files. The numbers are much higher than other processes. Is your Backgronder crashing for some reason?
As for the processing errors - Backgrounder has a tendency to generate corrupt file lines when it crashes or restarted. Such lines do not affect LogShark - it simply logs Processing Error and skips them.

So LogShark seems to be working as expected. If you find an issue with the Backgrounder, please check our KB for known issues or work with our amazing [Customer Support team](https://www.tableau.com/support) to resolve.

**Comment by avnikhil22** [comment]
Hi Xantrul,
We are using Tableau 2018.3 prod server. Does this mean that ART will populate only if we upgrade as it has more detailed information where we can link the utilization levels with workbooks?
This information is available on the dev server as we upgraded it to 2019.4 and we wanted to do some in-depth analysis for prod as we are facing stability issues.
We have isolated the Backgrounder on a separate server and the utilization levels are high during business hours but it did not crash.
Also, does SAML integration interfere with this process? 
What would be the limitations in that sense?
Thank you again for your continued support.

**Comment by Xantrul** [comment]
Hi Nikhil,

Yes - you most likely have to upgrade prod server in order to get most benefit from ART logging. ART workbook is based on additional information added to the logs in the recent versions, and older versions simply don't have this information in the logs.
In the meantime you could use Apache workbook to at least get an idea on how long each workbook takes to load and how often each one is accessed.

SAML integration should not affect LogShark in any way. It uses REST API to publish results to the Tableau Server and REST API works fine with SAML enabled.

**Comment by avnikhil22** [comment]
Well, Thank you for your reply. Will do the needful. 
Closing this thread.
