### ISSUE TITLE
In Logshark,in ServerTelemetry.twbx,what is the significance of local\ in Username list

### ISSUE THREAD

**Issue by javauser05** [tableau/Logshark#118]
I am using LogShark.Win.4.1.1911.09672 to analyze the tableau (Tableau Server Version: 2018.1.2 (20181.18.0615.1128) 64-bit Windows) logs.

   In ServerTelemetry.twbx, in the Session overview tab, When I click on ‘Username’ combo list as highlighted in the red color rectangle, I see the user names (e.g be1,be2 ...)that I have used to hit different tableau reports.

   I see username as be1 and local\be1, so just want to understand, what is the difference between two. what does local\ means?
![tableau](https://user-images.githubusercontent.com/21197534/82110667-9d000b80-975d-11ea-9bf8-7cacc42c03fc.png)

**Comment by beduke17** [comment]
you're seeing different methods of how the views are being called. It is very common for the full domain to be added for embedded views and the short name to be called when viewed directly within Tableau Server.

I would recommend using a regex/contains filter for this within Tableau Desktop of this is something being done continually.
