### ISSUE TITLE
Failed to start a new Hyper instance on AWS m5 and t3 family instance

### ISSUE THREAD

**Issue by jfrappier** [tableau/Logshark#121]
Hello,

Receiving the following message when trying to run logshark.

`info: LogShark.LogSharkRunner[0]
      Starting to process Log set C:\deploy\logs.zip
info: LogShark.LogSharkRunner[0]
      Generated Run ID: 20052714060817-ec2amaz-34n33kf-logs
info: LogShark.LogSharkRunner[0]
      Hyper Writer requested. Initializing writer factory...
fail: LogShark.LogSharkRunner[0]
      Exception occurred while initializing writer factory for writer 'hyper'. Exception message: Failed to start a new Hyper instance.
Context: 0x86a93465

Tableau.HyperAPI.HyperException: Failed to start a new Hyper instance.
Context: 0x86a93465
 ---> Tableau.HyperAPI.HyperException: The Hyper server process exited during startup with exit code: -1073741515
        Command-line: ""C:\deploy\LogShark\hyperd.exe" "-x" "date_style=MDY" "-x" "hyper_temp_directory_override=C:\Users\Administrator\AppData\Local\Temp\2\LogShark" "-x" "language=en_US" "-x" "log_config=file,json,all,hyperd,0" "--database=C:\Users\ADMINI~1\AppData\Local\Temp\2\hyper_db_UA3uX8hi" "--init=overwrite" "--init-user=tableau_internal_user" "--log-dir=Logs" "--no-password" "--skip-license" "--listen-connection" "tab.pipe://./pipe/auto" "--callback-connection" "tab.pipe://./pipe/{611B763E-0EC1-4626-AE39-7B9A9A8BE125}" "run" "

Context: 0x13cead20
   --- End of inner exception stack trace ---
   at Tableau.HyperAPI.Raw.Error.Check(IntPtr errp)
   at Tableau.HyperAPI.HyperProcess..ctor(String hyperPath, Telemetry telemetry, String userAgent, Dictionary`2 parameters)
   at LogShark.Writers.Hyper.HyperWriterFactory..ctor(String runId, LogSharkConfiguration config, ILoggerFactory loggerFactory)
   at LogShark.LogSharkRunner.GetWriterFactory(String runId)
   at LogShark.LogSharkRunner.ProcessLog()
info: LogShark.Program[0]

      -----Summary-----
      Run ID 20052714060817-ec2amaz-34n33kf-logs failed after running for 00:00:00.5154688. Reported problem: Exception occurred while initializing writer factory for writer 'hyper'. Exception message: Failed to start a new Hyper instance.
Context: 0x86a93465

      This problem is unexpected and it is not known whether or not it will go away if LogShark is run again.
      Information below might contain more details on what exactly failed

      -----Processing errors-----
      No errors occurred while processing log set`

Environment: AWS
Instance size: t3.2xlarge and m5.2xlarge (same error) 8vCPU/32GB
OS: Windows 2019
Logshark version: 4.1.2 (via Windows download link at https://tableau.github.io/Logshark/docs/logshark_install)

This is using all defaults, no changes were made to the LogSharkConfig.json

**Comment by mstromb** [comment]
Hi Jonathan,

I was able to reproduce your issue and have begun working with the Hyper team on a fix. I'll update this issue when I know more or have a workaround.

**Comment by mstromb** [comment]
After looking at this some more it seems that all you need to do is install the Microsoft Visual C++ runtime from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

While this dependency is documented it's not very visible and we'll take this as an opportunity to improve that.

Please let us know if installing the runtime doesn't fix your problem.

**Comment by jfrappier** [comment]
Thank you @mstromb - will try that and apologies for missing it.

**Comment by jfrappier** [comment]
Can confirm this was the missing step - thanks again!
