### ISSUE TITLE
No output when using --plugins Replayer

### ISSUE THREAD

**Issue by jfrappier** [tableau/Logshark#122]
Hello,

Trying to determine if the Replayer plugin is still supported. I see it in the repository, and LogShark does not fail when using that parameter but no output is generated.

In the logs I can see

info: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Writing to Json file ReplayerOutput\Playback_16_06_-19-33-23.json

Additional logs
      -----Summary-----
      Run ID 20061619332340-ec2amaz-lidka50-prod_logs_20200527 failed after running for 00:01:23.6195788. Reported problem: No workboo
ks were generated successfully.
      This problem is unexpected and it is not known whether or not it will go away if LogShark is run again.
      Information below might contain more details on what exactly failed
      
      -----Processing errors-----
      No errors occurred while processing log set
      
      -----Generated workbooks-----
      Workbook templates available: Apache; Art; Backgrounder; ClusterController; Config; Filestore; Hyper; Netstat; Postgres; Resourc
eManager; SearchServer; ServerTelemetry; Tabadmin; Vizportal; VizqlDesktop
      
      -----Log Reading Statistics-----
      Processed zip file compressed size: 453 MB
      Plugins that received any data: Replayer
      
      Apache                                            : Processed 3 files in 00:00:04.1416243. Elapsed: 00:00:04.1416243. Total size
: 38 MB. Processing at 9.18 MB/sec
      VizqlserverCpp                                    : Processed 16 files in 00:01:18.3930365. Elapsed: 00:01:18.3930365. Total siz
e: 1548 MB. Processing at 19.75 MB/sec
      
      -----Data Writers Statistics-----
But nothing in ..\output\

**Comment by Xantrul** [comment]
Hi Jonathan,

Replayer plugin outputs into `ReplayerOutput` dir instead of `Output`. Each run generates a single json file that is used by the Replayer tool. See [Replayer docs](https://community.tableau.com/docs/DOC-11048) for more info.

**Comment by jfrappier** [comment]
Hi, 

Simply a typo in my original post, no file is generated as stated in the logs.

This file

info: LogShark.Plugins.Replayer.ReplayerPlugin[0]
Writing to Json file ReplayerOutput\Playback_16_06_-19-33-23.json

Does not get generated.

**Comment by Xantrul** [comment]
Plz try to run Replayer plugin on this attached log set. Do you get json from it?
[logs_clean_tsm.zip](https://github.com/tableau/Logshark/files/4793759/logs_clean_tsm.zip)

**Comment by jfrappier** [comment]
This seems to have worked. Any way to determine what might be bad in our
logs?

**Comment by jfrappier** [comment]
Confirmed our logs still aren't able to produce any output. Are there any specific parameters I need to use for tsm maintenance to generate the logs in a format replayer expects? I seem to be coming up short finding repayer documentation (https://community.tableau.com/docs/DOC-11065)

**Comment by skostov-tableau** [comment]
Hi Jonathan,

I am one of the engineers who worked on the Replayer plugin's implementation.

I need some more details from your logs that don't produce the json output. Do you see some exceptions in that log, e.g. NullReferenceException or ArgumentNullException? If you do, please share the lines around them to better give me an idea about what could be going bad.

Thank you,
Stoyko

**Comment by skostov-tableau** [comment]
Other things that could be useful in my investigation - the output log may have lines like this:

Processing file node1/gateway_0.20192.19.0718.15431126834964030102991/logs/access.2019_08_09_00_00_00.log
Processing file node1/vizqlserver_0.20192.19.0718.15438685063481366773782/logs/nativeapi_vizqlserver_1-1_2019_08_09_00_00_00.txt

These are the 2 types of files that the Replayer needs: access and nativeapi_vizqlserver.

If you could provide some excerpts from one of each kind of files, it may help me see where the parsing is choking.

Feel free to mask sensitive info (PII), e.g. user name, machine name, etc.
Thanks!

**Comment by jfrappier** [comment]
Hi @skostov-tableau 

I do not see any exceptions. I do see "Processing file node1/vizqlserver"

`o: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_24_00_00_00.txt`

Full log
`
PS C:\Users\Administrator> C:\deploy\LogShark\LogShark.exe C:\deploy\prod_logs_20200527.zip --plugins Replayer
info: LogShark.LogSharkRunner[0]
      Starting to process Log set C:\deploy\prod_logs_20200527.zip
info: LogShark.LogSharkRunner[0]
      Generated Run ID: 20063013013336-ec2amaz-foo-prod_logs_20200527
info: LogShark.LogSharkRunner[0]
      Hyper Writer requested. Initializing writer factory...
info: LogShark.LogSharkRunner[0]
      Using temp folder `C:\Users\Administrator\AppData\Local\Temp\2\LogShark`
info: LogShark.LogParser.TableauLogsExtractor[0]
      Starting TableauLogsExtractor for log set `C:\deploy\prod_logs_20200527.zip`
info: LogShark.LogParser.TableauLogsExtractor[0]
      Provided log set appears to be zip file
info: LogShark.LogParser.TableauLogsExtractor[0]
      Looking for known nested zip files inside zip file 'C:\deploy\prod_logs_20200527.zip'
info: LogShark.LogParser.TableauLogsExtractor[0]
      No known nested zip files found in 'C:\deploy\prod_logs_20200527.zip
info: LogShark.LogParser.TableauLogsExtractor[0]
      Completed TableauLogsExtractor for log set `C:\deploy\prod_logs_20200527.zip`
info: LogShark.Plugins.PluginInitializer[0]
      Starting to load plugins for string: Replayer
info: LogShark.Plugins.PluginInitializer[0]
      1 plugins loaded: Replayer
info: LogShark.LogSharkRunner[0]
      Based on requested plugins, the following log types will be processed: Apache, VizqlserverCpp
info: LogShark.LogSharkRunner[0]
      Starting to process Apache logs
info: LogShark.LogParser.TableauLogsReader[0]
      Starting to process log set part `C:\deploy\prod_logs_20200527.zip` for Apache logs
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/gateway_0.20192.19.0518.06392913226452077960687/logs/access.2020_05_25_00_00_00.log
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/gateway_0.20192.19.0518.06392913226452077960687/logs/access.2020_05_25_00_00_00.log in 00:00:01.6268909 (17 MB, 80123 lines, 10.45 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/gateway_0.20192.19.0518.06392913226452077960687/logs/access.2020_05_26_00_00_00.log
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/gateway_0.20192.19.0518.06392913226452077960687/logs/access.2020_05_26_00_00_00.log in 00:00:01.7698777 (20 MB, 92369 lines, 11.30 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/gateway_0.20192.19.0518.06392913226452077960687/logs/access.2020_05_27_00_00_00.log
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/gateway_0.20192.19.0518.06392913226452077960687/logs/access.2020_05_27_00_00_00.log in 00:00:00.0247930 (0 MB, 1366 lines, 0.00 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing `C:\deploy\prod_logs_20200527.zip` for Apache logs. Processed 3 files in 00:00:03.4212065. Elapsed: 00:00:03.4212065. Total size: 38 MB. Processing at 11.11 MB/sec
info: LogShark.LogSharkRunner[0]
      Done processing Apache logs. Processed 3 files in 00:00:03.4212065. Elapsed: 00:00:03.4212065. Total size: 38 MB. Processing at 11.11 MB/sec
info: LogShark.LogSharkRunner[0]
      Starting to process VizqlserverCpp logs
info: LogShark.LogParser.TableauLogsReader[0]
      Starting to process log set part `C:\deploy\prod_logs_20200527.zip` for VizqlserverCpp logs
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_24_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_24_00_00_00.txt in 00:00:00.3305445 (0 MB, 1187 lines, 0.00 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_25_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_25_00_00_00.txt in 00:00:01.0929339 (25 MB, 41971 lines, 22.87 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_26_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_26_00_00_00.txt in 00:00:14.1409099 (317 MB, 580155 lines, 22.42 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_27_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-0_2020_05_27_00_00_00.txt in 00:00:00.0013450 (0 MB, 56 lines, 0.00 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_24_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_24_00_00_00.txt in 00:00:00.0119904 (0 MB, 1232 lines, 0.00 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_25_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_25_00_00_00.txt in 00:00:01.7992391 (40 MB, 66886 lines, 22.23 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_26_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_26_00_00_00.txt in 00:00:15.0101608 (352 MB, 593326 lines, 23.45 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_27_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-1_2020_05_27_00_00_00.txt in 00:00:00.7699462 (17 MB, 29036 lines, 22.08 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_24_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_24_00_00_00.txt in 00:00:00.0115507 (0 MB, 1235 lines, 0.00 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_25_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_25_00_00_00.txt in 00:00:15.9166404 (375 MB, 734571 lines, 23.56 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_26_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_26_00_00_00.txt in 00:00:02.6431293 (64 MB, 102094 lines, 24.21 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_27_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-2_2020_05_27_00_00_00.txt in 00:00:01.3634401 (33 MB, 52179 lines, 24.20 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_24_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_24_00_00_00.txt in 00:00:00.0107785 (0 MB, 1205 lines, 0.00 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_25_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_25_00_00_00.txt in 00:00:00.7189114 (17 MB, 27767 lines, 23.65 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_26_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_26_00_00_00.txt in 00:00:12.9033304 (296 MB, 495211 lines, 22.94 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_27_00_00_00.txt
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing file node1/vizqlserver_0.20192.19.0518.06392751812560705202560/logs/nativeapi_vizqlserver_1-3_2020_05_27_00_00_00.txt in 00:00:00.3373336 (7 MB, 12401 lines, 20.75 MB/s)
info: LogShark.LogParser.TableauLogsReader[0]
      Completed processing `C:\deploy\prod_logs_20200527.zip` for VizqlserverCpp logs. Processed 16 files in 00:01:07.0621731. Elapsed: 00:01:07.0621731. Total size: 1548 MB. Processing at 23.08 MB/sec
info: LogShark.LogSharkRunner[0]
      Done processing VizqlserverCpp logs. Processed 16 files in 00:01:07.0621731. Elapsed: 00:01:07.0621731. Total size: 1548 MB. Processing at 23.08 MB/sec
info: LogShark.LogSharkRunner[0]
      Telling all plugins to complete processing of any cached data
info: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Processing 136 apache source lines and 110 begin command controller, 137 server telemetry, 5406 lock session, 0 end bootstrap vizqlserver events
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:2
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:2
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:2
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:2
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:3
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:1
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID1:0
dbug: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Getting commands for vizqlserver session NotRealSessionID-1:1

----removed several lines all the same as above for readability jf ----

info: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Serializing Json replay sessions
info: LogShark.Plugins.Replayer.ReplayerPlugin[0]
      Writing to Json file ReplayerOutput\Playback_30_06_-13-01-34.json
info: LogShark.LogSharkRunner[0]
      Completed reading log set and generating data
info: LogShark.LogParser.TableauLogsExtractor[0]
      Disposing log extractor temporary files...
info: LogShark.LogParser.TableauLogsExtractor[0]
      Log extractor temporary files disposed
info: LogShark.LogSharkRunner[0]
      Plugins that had any data sent to them: Replayer
info: LogShark.Writers.Hyper.HyperWorkbookGenerator[0]
      Starting to generate workbooks with results...
fail: LogShark.LogSharkRunner[0]
      No workbooks were generated successfully.
info: LogShark.Program[0]

      -----Summary-----
      Run ID 20063013013336-ec2amaz-foo-prod_logs_20200527 failed after running for 00:01:12.8016924. Reported problem: No workbooks were generated successfully.
      This problem is unexpected and it is not known whether or not it will go away if LogShark is run again.
      Information below might contain more details on what exactly failed

      -----Processing errors-----
      No errors occurred while processing log set

      -----Generated workbooks-----
      Workbook templates available: Apache; Art; Backgrounder; ClusterController; Config; Filestore; Hyper; Netstat; Postgres; ResourceManager; SearchServer; ServerTelemetry; Tabadmin; Vizportal; VizqlDesktop

      -----Log Reading Statistics-----
      Processed zip file compressed size: 453 MB
      Plugins that received any data: Replayer

      Apache                                            : Processed 3 files in 00:00:03.4212065. Elapsed: 00:00:03.4212065. Total size: 38 MB. Processing at 11.11 MB/sec
      VizqlserverCpp                                    : Processed 16 files in 00:01:07.0621731. Elapsed: 00:01:07.0621731. Total size: 1548 MB. Processing at 23.08 MB/sec

      -----Data Writers Statistics-----
`

**Comment by skostov-tableau** [comment]
Thanks Jonathan. The lack of exceptions makes it hard to troubleshoot. 

I'd like to ask you to try 2 more things:
1. Can you search the entire folder under Replayer for file Playback_30_06_-13-01-34.json? (this is the one the tool reported to be writing to).
2. If not found, it's possible (though remotely) that the sessions in access and vizqlserver logs don't intersect. Choose one session ID reported by the tool (e.g. NotRealSessionID-1:1, but with the real ID) and search the gateway_* files and the vizqlserver_* files for that session ID. Make sure it is found in both.

If it is found in both, can you please provide examples of each line? E.g. on the example I ran, I use session ID  84673FA7D7284E03B5C77EF472317037-1:1, and 2 example lines are:

logs\vizqlserver_node1-1.log:2019-08-09 21:29:02.411 +0000 (Default,---redacted---,84673FA7D7284E03B5C77EF472317037-1:1,XU3eaafymHlRj@z8RHr-4wAAAe4) pool-15-thread-2 : INFO  wgsessionId=R963KTxFQ3WXkDj24_5z_w com.tableausoftware.model.vizql.session.IVizqlSessionManager - activity=session-destroyed sess=84673FA7D7284E03B5C77EF472317037-1:1 user=---redacted--- site=Default site_id=1 guest=0 wg_session_id=R963KTxFQ3WXkDj24_5z_w session_type=WORKBOOK_VIEW workbook_name=Regional workbook_id=1 status=1

logs\access.2019_08_09_00_00_00.log:ec2amaz-t1i4g5m fe80::a481:6c14:1c46:746 - 2019-08-09T20:58:17.638 "Coordinated Universal Time" 80 "POST /vizql/w/Regional/v/Obesity/bootstrapSession/sessions/84673FA7D7284E03B5C77EF472317037-1:1 HTTP/1.1" "-" 200 7822 "812" 4775397 XU3eaafymHlRj@z8RHr-4wAAAe4

(again, please redact any sensitive/PII data).

Thanks
Stoyko

**Comment by jfrappier** [comment]
Hi Stoyko,

3rd time is a charm it seems, it generated this time when we re-ran it to generate some logs. Thanks for your help and direction.
