### ISSUE TITLE
Link 4.2 from front page (currently still pointing to 4.1)

### ISSUE THREAD

**Issue by stelios-c** [tableau/Logshark#127]
https://tableau.github.io/Logshark/docs/logshark_install.html has not been updated. Windows download link points to https://github.com/tableau/Logshark/releases/download/v4.1.2/LogShark.Win.4.1.2.zip , when https://github.com/tableau/Logshark/releases/tag/v4.2 is now available, likewise for Mac.

**Comment by bermetj** [comment]
@stelios-c , thanks for the catch! Fixed.
