### ISSUE TITLE
Logshark - email/sns/slack notification

### ISSUE THREAD

**Issue by limmt** [tableau/Logshark#128]
As per title, can have notification embedded to communication tools notification. (preferable slack). So, as we tableau admin will have better trigger points. # Prevention better than recover.

**Comment by Xantrul** [comment]
Hi Lim,

Could you provide more details on your use case and the request? Are you automating collection of logs and processing them with LogShark? Are you using Postgres or Hyper as output? Do you have a particular condition in mind you would like to get alerts for?

**Comment by Xantrul** [comment]
I gonna close this for now as request is unclear. Please feel free to reopen with more details about the request.
