### ISSUE TITLE
MongoDB fail

### ISSUE THREAD

**Issue by Sivivatu** [tableau/Logshark#13]
I have installed logshark onto my local laptop and am unable process any logs at all. when I run logshark i get the error message:
`Unable to retrieve logset metadata from MongoDB: An exception occurred while opening a connection to the server. ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:27017`

Is there anything I have done wrong or need to change?

**Comment by jmangue** [comment]
Hi Sivavatu,

So by default, Logshark spins up a MongoDB process on that port at runtime.  Could something on your system be blocking the MongoDB instance from starting, or is another process bound to that port?  Are there any other errors in the Logshark logs?

**Comment by Sivivatu** [comment]
that is what I thought should be happening but I dont think the MongoDB was starting properly on start up with the normal `logshark c:\file` command. when i added the --startlocalmongo switch it worked perfectly

**Comment by jmangue** [comment]
Oh cool, glad to hear it's working now!

If you want to change it so that --startlocalmongo happens by default, you can edit Logshark.config and change the "<LocalMongo **useAlways="false"** from false to true.

**Comment by jmangue** [comment]
Closing this one out.

**Comment by Sivivatu** [comment]
thanks @jmangue the config change is what I was missing.
