### ISSUE TITLE
LogShark command failing to publish workbook to tableau server

### ISSUE THREAD

**Issue by surya421** [tableau/Logshark#131]
Hi All,

I am using LogShark to analyse the server logs generated. Installed it and configured it on windows.

Aware that Tableau does not provide any official support regarding LogShark

I am Using tableau server 2020.2.1 version and came to know from one of the tableau official article that REST API version supported by that version is 3.8

Trying to publish the workbooks (to the tableau server) which are generated as the outputs after running the LogShark on the ziplogs file, however got the error saying http error and found that the error is due to incompatible REST API version 2.8.

It is taking 2.8 version.. How to make it take the API version 3.8.

Have tried putting 3.8 version in the tableau server URL in the config json file of LogShark but no use, and noticed that 2.8 is getting appended as the suffix to 3.8 in the same URL when the command is run. Found that observation in the log file of the LogShark run. Please suggest the way forward

Thanks in advance

Surya

**Comment by Xantrul** [comment]
Hi,
Tableau Server 2020.2.1 supports REST API version 2.8 just fine, so the problem should be somewhere else. The first thing to check is usually the config: make sure that `Url` parameter only contains url of the server, without site or any other info (i.e. `https://tableau.company.com/`). `Site` parameter should not be empty (when using default site, `default` should be used as a value).
If this doesn't help - try to do at least these two steps through REST API manually and see if there are any issues:
-  Authenticate to a site
-  Create a project

Also, what error message do you see?
