### ISSUE TITLE
Issue processing backgrounder logs server version - 2020.2.4 (20202.20.0721.1350)

### ISSUE THREAD

**Issue by andypick** [tableau/Logshark#132]
Hi, I am getting a number of errors in the backgrounder process. The produced workbook is blank. The repeated error I am getting is "Failed to process string as Backgrounder event. This is expected for logs prior to 10.4" Has anyone experienced this before? Have tried both running the full ziplog and just using the background plugin, same error occurs. Thanks

**Comment by Xantrul** [comment]
Hi,
Only the latest version of LogShark (4.2) published here is able to process Backgrounder logs from 2020.x. Plz make sure that you are running the latest version.
Similar issue was reported not that long ago (https://github.com/tableau/Logshark/issues/129) and the problem there was PATH variable pointing at the old version. One way to rule out all issues like that is to try the latest version of LogShark on the different machine that never had LogShark before.

If the issue still reproduces on 4.2 - please lmk.
