### ISSUE TITLE
Logshark fails to publish workbooks on Tableau server

### ISSUE THREAD

**Issue by malexandrov69** [tableau/Logshark#134]
I am trying to run Logshark and to publish the outcome workbooks to Tableau Server.
Publishing fails with error:

Exception encountered when attempting to sign in or create the project: Http error returned while sending a request. Error reported: Call failed with status code 404 (Not Found): POST **https://preprod-visualize.drei.com/auth/signin#/site/api/2.8**. Response body <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /auth/signin was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
It looks like url constructed to do the REST API call is not correct.
The correct one should look like this (tested in Postman): **https://preprod-visualize.drei.com/#/api/2.8/auth/signin**

The setting in LogSharkConfig.json are as follows:

"Url": "https://preprod-visualize.drei.com/#",
    "Site": "Default",
...

Please advice how to enter the url in order get correct Rest API call!

**Comment by Xantrul** [comment]
The URL from the error message definitely looks incorrect. Not sure how it ended up like this tbh. Code that generates this URL looks like `var apiUrl = $"{tableauServerInfo.Url}/api/{ApiVersion}";`, and then we append `auth/signin`  to it.

Plz remove "/#" from the `Url` parameter, leaving only `https://preprod-visualize.drei.com/`. If this doesn't help, try changing Site parameter to empty string `""`. Also make sure that this is THE config file used by LogShark (we've seen issues in the past where multiple versions of LogShark were present on the machine and PATH variable was pointing at the wrong version)

**Comment by malexandrov69** [comment]
Hi,

Thank you for your feedback!
It worked with following settings:

"Url": "https://preprod-visualize.drei.com/",
"Site": ""

**Comment by malexandrov69** [comment]
Solved
