### ISSUE TITLE
Feature Request: Switch to Disable Query field getting truncated to 1024 characters

### ISSUE THREAD

**Issue by rayrandall** [tableau/Logshark#15]
The Query column in the Vizql_End_Query table and the Query_Abstract column and Query_Compiled columns in the vizql_qp_batch_summary_job table are getting truncated to 1024 characters. 

We'd like the complete query to be logged as a partial query doesn't have much utility. An option to disable the truncation or set a new limit would be wonderful.

Thank you!
Ray

        public VizqlEndQuery(BsonDocument document)
        {
            ValidateArguments("end-query", document);

            SetEventMetadata(document);
            BsonDocument values = BsonDocumentHelper.GetValuesStruct(document);

            Query = BsonDocumentHelper.TruncateString(BsonDocumentHelper.GetString("query", values), 1024);
            ProtocolId = BsonDocumentHelper.GetNullableLong("protocol-id", values);
            Cols = BsonDocumentHelper.GetInt("cols", values);
            Rows = BsonDocumentHelper.GetInt("rows", values);
            QueryHash = BsonDocumentHelper.GetNullableLong("query-hash", values);
            Elapsed = BsonDocumentHelper.GetDouble("elapsed", values);
        }

**Comment by jmangue** [comment]
Thanks Ray!  I believe this truncation was to avoid performance issues on logsets with extremely large queries (see MDX queries).  We'll likely address this by including a plugin argument flag to override the default behavior with a custom limit.

**Comment by jmangue** [comment]
This has been mitigated somewhat by increasing the limit to 10000 characters in [Logshark v2.0](https://github.com/tableau/Logshark/releases/tag/v2.0).
