### ISSUE TITLE
Appending to existing DB

### ISSUE THREAD

**Issue by Sivivatu** [tableau/Logshark#16]
I'm updating my logshark database regularly using the script 
`logshark <logs.zip_name> --dbname <company_name> -f --parseall`
I just want to confirm if I use a log set with overlapping dates, does the get duplicated in the Postgres DB or is there sufficient intelligence to account for this (eg primary key update based on identifiers)?

**Comment by jmangue** [comment]
Hi Sivivatu,

I can confirm that the data does not get duplicated.  Each table has an "event hash" that is unique constrained, specifically to avoid this.

The only thing that gets a bit messed up when you regularly append like this is the tabadmin version data used in the Tabadmin workbook.  This is a known issue.

-Justin

**Comment by Sivivatu** [comment]
Brilliant thanks @jmangue 
that was what I thought I just wanted to confirm for certain. I will keep an eye out for the fix to the tabadmin updating, any idea on time frames for this?

**Comment by jmangue** [comment]
No problem, @Sivivatu!

We don't have an ETA on a publicly released fix for the tabadmin version appending issue at this time, but keep an eye out for it in the release notes of future versions.
