### ISSUE TITLE
Unable to find package Tools.TableauServerRestApi. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by vinay4191** [tableau/Logshark#165]
#11 [build 4/4] RUN dotnet publish "LogShark/LogShark.csproj" -r linux-x64 --self-contained false -c Release /p:Version=4.2.3 -o out
#11 sha256:bec364d9ce5e3de5b88ac5f53a746a29c118c688ca14e5bc969b6cdd21bd7be0
#11 0.573 Microsoft (R) Build Engine version 16.7.3+2f374e28e for .NET
#11 0.573 Copyright (C) Microsoft Corporation. All rights reserved.
#11 0.573 
#11 1.040   Determining projects to restore...
#11 9.920   Restored /app/LogShark.Shared/LogShark.Shared.csproj (in 8.64 sec).
#11 88.01 /app/LogShark/LogShark.csproj : error NU1101: Unable to find package Tools.TableauServerRestApi. No packages exist with this id in source(s): nuget.org
#11 88.17   Failed to restore /app/LogShark/LogShark.csproj (in 1.45 min).
#11 ERROR: executor failed running [/bin/sh -c dotnet publish "LogShark/LogShark.csproj" -r linux-x64 --self-contained false -c Release /p:Version=4.2.3 -o out]: exit code: 1
------
 > [build 4/4] RUN dotnet publish "LogShark/LogShark.csproj" -r linux-x64 --self-contained false -c Release /p:Version=4.2.3 -o out:
------
executor failed running [/bin/sh -c dotnet publish "LogShark/LogShark.csproj" -r linux-x64 --self-contained false -c Release /p:Version=4.2.3 -o out]: exit code: 1
vgourishetty-macbookpro:logshark vgourishetty$

**Comment by KarthikINV** [comment]
Is this issue resolved or in discussion, I'm also facing the same issue could you please help

**Comment by vinay4191** [comment]
Hi Karthik, This issue is resolved and I was able to install logshark and generate the output out of it.

**Comment by KarthikINV** [comment]
Hi after checking out to previous version i was able to resolve the issues, but my main thing for this new version was wbk related to flow logs was introduced, is there any way i can use this version and generate flow related workbook

**Comment by TILDEschalkb** [comment]
Hi, I'm getting the same error when installing Logshark 4.2.3 on Ubuntu 20.04. How did you solve this? 
Error is the same when running with all 4.2.x versions: 

dotnet publish LogShark -c Release -r linux-x64 /p:Version=4.2.3 --self-contained true
Microsoft (R) Build Engine version 16.7.3+2f374e28e for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/tmp/Logshark/LogShark/LogShark.csproj : error NU1101: Unable to find package Tools.TableauServerRestApi. No packages exist with this id in source(s): nuget.org
  Failed to restore /tmp/Logshark/LogShark/LogShark.csproj (in 1.12 sec).
  Restored /tmp/Logshark/LogShark.Shared/LogShark.Shared.csproj (in 61 ms).

**Comment by zhuoyanggao** [comment]
Hi @KarthikINV , @TILDEschalkb  @vinay4191 

Wonder if below work-around would help:

Revert all changes in logshark/Logshark.csproj locally, and retry build.

We might be releasing a patch for this in the coming weeks.
