### ISSUE TITLE
Failed to initialize Logshark request processor

### ISSUE THREAD

**Issue by SamanthaGun** [tableau/Logshark#17]
Hi there

Even though I have created logshark account and granted relevant permission levels to postgres data base, I am getting the error "**_Failed to initialize Logshark request processor!
Please check to make sure that the results database was configured correctly_**" Excerpt from Logshark.log file is given below.

--------------------

017-06-05 11:56:21,064 (null) [1] DEBUG Logshark.CLI.Program - Logshark execution arguments: D:\Tableau\ServerLogs\NonProdServer_5-06-17.zip
2017-06-05 11:56:21,110 (null) [1] INFO Logshark.Config.LogsharkConfigReader - Loading Logshark user configuration..
2017-06-05 11:56:21,224 (null) [1] DEBUG Logshark.Connections.PostgresConnectionInfo - Attempting to open connection to Postgres database 'localhost:5432\postgres' using user account 'logshark'..
2017-06-05 11:56:21,293 (null) [1] FATAL Logshark.CLI.LogsharkCLI - Failed to initialize Logshark request processor!
Please check to make sure that the results database was configured correctly. (Exception has been thrown by the target of an invocation.)
2017-06-05 11:56:21,293 (null) [1] DEBUG Logshark.CLI.LogsharkCLI - Logshark.Exceptions.DatabaseInitializationException: Failed to initialize Logshark request processor!
Please check to make sure that the results database was configured correctly. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---

-------------

Any help would be greatly appreciated.

Thanks
Samantha

**Comment by jmangue** [comment]
Hi Samantha,

FIPS Mode is a setting in Windows that governs which encryption/hashing/digital signing can be used. 
 Logshark itself is FIPS-compliant, but Postgres uses MD5 hashing for it's username/password authentication, which causes problems on Windows systems where FIPS mode is enabled.

I believe disabling FIPS mode on the system hosting Postgres would likely resolve your problem, but of course, you should first make sure this is acceptable from a security standpoint.  FYI -- Microsoft actually [no longer recommends enabling FIPS mode](https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/).

This setting can be disabled via a local security policy; [here's an easy-to-follow set of instructions](http://docs.trendmicro.com/all/ent/sc/v3.0/en-US/cmcolh/t_fips.html).

Hope that helps!
-Justin

**Comment by SamanthaGun** [comment]
Thanks heaps Justin :+1: 

It sure did help - now the difficult part which is making IT security to agree with this approach
