### ISSUE TITLE
Cluster Controller Postgres Commands Viz not populating

### ISSUE THREAD

**Issue by darrenatcsus** [tableau/Logshark#20]
Hello all,

I am using Logshark and loving it! What great tool for us "accidental" Tableau admins. In the ClusterController workbook, the Cluster Controller Postgres Commands viz is not populating. I think it should because I got an email from the server "Tableau Server : Status change for multiple services on "myserver". When i look at the Cluster Controller Errors and Zookeeper Errors, they show errors that correspond the time of the Tableau Server notification email.  But nothing Cluster Controller Postgres Commands viz. Can anyone explain why? 

btw, this is the error as displayed in the Cluster Controller Errors dashboard that must have caused the email:
Exception from ZooKeeper ruokjava.io.IOException: Exception while executing four letter word: ruok

Thanks,
Darren

**Comment by jmangue** [comment]
Hey Darren,

Glad that you're finding Logshark useful!

Regarding the "Cluster Controller Postgres Commands" worksheet... this sheet shows instances of Cluster Controller issuing start, stop, and failover commands to Tableau Server's Postgres database.  In a healthy server, this only happens during server startup & shutdown, so it is pretty common and expected for this worksheet to be empty if your logset doesn't cover the time-frame of starting or stopping your server.  Hope that answers your question!

**Comment by jmangue** [comment]
Closing this one out as answered.
