### ISSUE TITLE
Update to user guide instruction 

### ISSUE THREAD

**Issue by james145643** [tableau/Logshark#26]
On the page https://tableau.github.io/Logshark/docs/logshark_run
The instructions say to 'Run Setup_Logshark_v2.exe .
However this is the installation file - instead the user needs to open the cmd and cd to the bin directory within the directory where Logshark was installed (location of logshark.exe) They can then run the described commands e.g. logshark Target options.
Thanks,
James

**Comment by jmangue** [comment]
Good catch, @james145643 !  Thanks for reporting it.

This has been fixed in f734971a155d3e372b368bdbc4363d81425f811e
