### ISSUE TITLE
Not able to run Logshark to process the log files

### ISSUE THREAD

**Issue by aelmoun2** [tableau/Logshark#29]
Hi,

I am in the process of testing Logshark in my machine. I have edited the Logshark.config as mentioned in the Guide. However, when I tried to run the following I don't get anything:

C:\Program Files\Logshark>logshark C:\Users\Alex\Downloads\mylogs10262017 --startlocalmongo
Loading Logshark user configuration..
Target must be a valid file, directory or MD5 hash!
C:\Program Files\Logshark>

Please let me know if I am missing anything.

Thank you
Alex

**Comment by jmangue** [comment]
Hi @aelmoun2 ,

It looks like Logshark is unable to determine if the directory you pointed it at ` C:\Users\Alex\Downloads\mylogs10262017` is a valid logset.  Is that directory the root of a Desktop or Server logset?

**Comment by aelmoun2** [comment]
Hi Jmangue,

That is the root of a desktop, not to to the bin Directory where the logs are being generated.
I am testing Logshark through my machine first before we do same in tableau server.
I have generated the logs from tableau server, and coiped the zip file into my local machine.

**Comment by jmangue** [comment]
For desktop logs, the directory you pass to Logshark needs to contain either `log.txt` or `Logs\log.txt` in the root for it to be correctly identified as a Tableau Desktop logset.  I'd recommend checking to make sure that is the case for `C:\Users\Alex\Downloads\mylogs10262017`.

For Server logs, any archive generated by `tabadmin ziplogs` or `Generate Snapshot` should work just fine.

**Comment by aelmoun2** [comment]
I did follow the steps provided in the guide under "Run Logshark to process the log files":https://tableau.github.io/Logshark/docs/logshark_run
When I get to step 3, I get the below error:

"C:\Program Files\Logshark>logshark.exe
Loading Logshark user configuration..
No logset target specified! See 'logshark --help' for usage examples."

I am not runnig this in tableau server, I am running everything in my local desktop.
I have ran the tabadmin ziplogs and generated the logs, then copied and pasted the logs to my desktop machine.

I am not sure what I am doing wrong,

**Comment by jmangue** [comment]
Hi @aelmoun2 -- you need to pass logshark.exe a path to your ziplogs, as shown in the example in step 3 on the page you linked.  For example:

`logshark C:\Logs\logs.zip --startlocalmongo`

Let me know how it goes!

**Comment by aelmoun2** [comment]
Hi Jmangue -- I run the following as mentioned in step 3, but I get an error:
(C:\Logs\mylogs10262017.zip is the path to my log file)

C:\Program Files\Logshark>logshark C:\Logs\mylogs10262017.zip --startlocalmongo
Loading Logshark user configuration..
Failed to initialize Logshark request processor!
Please check to make sure that the results database was configured correctly. (Failed to open connection to Localhost:5433: 28000: role "logshark" does not exist)

**Comment by jmangue** [comment]
Hey @aelmoun2 , 

It seems that the logshark user does not exist in your database.  Did you follow the steps in the user guide for configuring [PostgreSQL for Logshark](https://tableau.github.io/Logshark/docs/logshark_postgres)?  That should get you squared away.

**Comment by aelmoun2** [comment]
Hi Jmangue, 

I have added Logshark user to the db with "password" as the password, but unfortunately still getting same error. Please see below my Logshark.config file, Please let me know if anything is wrong:

<?xml version="1.0"?>

<LogsharkConfig xmlns="logshark">
  <MongoConnection poolSize="200" timeout="60" insertionRetries="3">
    <Servers>
      <Server address="localhost" port="27017" />
    </Servers>
    
    
  </MongoConnection>
  <PostgresConnection tcpKeepalive="60">
    <Server address="Localhost" port="5433" />
    <User username="logshark" password="password" />
  </PostgresConnection>
  <TableauConnection protocol="https" publishingTimeoutSeconds="300">
    <Server address="tableautest.xxxxx.com" port="443" site="CustomServerAdminViews" />
    <User username="Adam000" password="Password456" />
  </TableauConnection>
  <RunOptions>
    <LocalMongo useAlways="false" purgeOnStartup="true" />
    <Tuning>
      <FilePartitioner concurrencyLimit="4" maxFileSizeMb="250" />
      <FileProcessor concurrencyLimitPerCore="1" />
    </Tuning>
  </RunOptions>
  <ArtifactProcessorOptions>
    <ArtifactProcessor name="TableauDesktopLogProcessor">
      <DefaultPlugins>
        <Plugin name="CustomWorkbooks" />
        <Plugin name="DataEngine" />
        <Plugin name="VizqlDesktop" />
      </DefaultPlugins>
    </ArtifactProcessor>
    <ArtifactProcessor name="TableauServerLogProcessor">
      <DefaultPlugins>
        <Plugin name="Apache" />
        <Plugin name="Backgrounder" />
        <Plugin name="ClusterController" />
        <Plugin name="Config" />
        <Plugin name="CustomWorkbooks" />
        <Plugin name="Filestore" />
        <Plugin name="Netstat" />
        <Plugin name="Postgres" />
        <Plugin name="ResourceManager" />
        <Plugin name="SearchServer" />
        <Plugin name="Tabadmin" />
        <Plugin name="Vizportal" />
        <Plugin name="VizqlServer" />
        
      </DefaultPlugins>
    </ArtifactProcessor>
  </ArtifactProcessorOptions>
</LogsharkConfig>

I really appreciate your assistance into this.

Thank you

**Comment by jmangue** [comment]
Unfortunately, your config did not come through here.

Currently it looks like whatever user you've specified in Logshark.config doesn't match what's in the database.  I'd recommend checking the casing and spelling on the database user you set up versus what you've specified in Logshark.config; they need to match exactly.

**Comment by aelmoun2** [comment]
Hi Jmangue,

Can you please see if I am doing anything wrong 

![image](https://user-images.githubusercontent.com/22208518/34011732-0af243ca-e0df-11e7-87d4-48ffadc979eb.png)

**Comment by aelmoun2** [comment]
![image](https://user-images.githubusercontent.com/22208518/34011771-316847b6-e0df-11e7-8f33-5bfefaa8fd2d.png)

**Comment by jmangue** [comment]
Can you please verify that the "logshark" role has the following permissions set: **Can create databases** and **Can login**

**Comment by cbeck513** [comment]
Logshark is unable to read 2018.1 log files.
![image](https://user-images.githubusercontent.com/11356204/39128285-69b10a8e-46d5-11e8-9637-7d7964affe4f.png)

**Comment by yvraprasad** [comment]
I have similar issue...
No compatible artifact processor found for payload! Is this a valid logset ?

Please respond what modifications to be done ?

**Comment by jmangue** [comment]
Hi everyone, the latest release of Logshark (https://github.com/tableau/Logshark/releases/tag/v2.1) can now read 2018.1 files.  Please open a new issue if you need additional help on this, thanks!
