### ISSUE TITLE
Feature Request: Installation as stand-alone or without Admin rights

### ISSUE THREAD

**Issue by philshem** [tableau/Logshark#3]
Many of us Managing Tableau Server installations are not Admins of our own Client machines (and sometimes not even Server machines).

Unfortunately, I'm unable to install Logshark from my client machine, and am concerned about installing on my Server machine (because of performance, server stability, etc).

For that reason, I'd like to suggest a stand-alone or admin-less installation. (the same goes for Tableau Desktop!) I understand that it is not technically-practical but it is business-important.

![2016-11-03 16_44_37-logshark setup](https://cloud.githubusercontent.com/assets/4997607/19973365/4b50c502-a1e5-11e6-89b5-9585ceeccef6.png)

**Comment by jmangue** [comment]
Hi philshem,

Thanks for the feedback.  We totally understand your pain on this, and understand that admin privileges in Enterprise deployments can be tough to come by.

Logshark does certain operations which are not typically in the realm of local user space (i.e. potentially spinning up a local MongoDB instance).  Requiring local administrator privileges is the most surefire way to guarantee that the application has the permissions it needs.  A version that does not require admin is certainly possible but would be a bit tricky.

One potential workaround for someone in your situation would be to ask your IT for a sandbox VM that you have a local admin account on.

I'd like to leave this issue open as a suggestion in case others would like to request this.
