### ISSUE TITLE
Logshark run fails due to GuidRepresentation error in LogsetValidator

### ISSUE THREAD

**Issue by daVinciCEB** [tableau/Logshark#32]
I've tried running Logshark on my computer's Tableau logs, but I am receiving the following exception:

`The GuidRepresentation for the reader is CSharpLegacy, which requires the binary sub type to be UuidLegacy, not UuidStandard`

According to the Logshark Logs, this exception is causing it to think mongo contains invalid log data and the run fails.

**Comment by daVinciCEB** [comment]
@jmangue I was running it against the most recent MongoDB server available at the time I wrote this, I believe it was 3.6.0?
I forked Logshark and started taking a look at the code to see if I could use [this solution](https://stackoverflow.com/questions/16369308/use-guidrepresentation-standard-with-mongodb), but it still was giving me errors...
Do you have a specific MongoDB version that you guys are using to run Logshark?

**Comment by craigbloodworth** [comment]
I've reproduced this error on a new install using MongoDB v3.6.2

**Comment by jmangue** [comment]
Yeah, this is sounding like a compatibility issue with newer versions of MongoDB.  I'll check it out, but in the meantime one way to verify this would be to try running Logshark using the "--startlocalmongo" flag to see if the error still happens, as the version of MongoDB bundled with Logshark is a little older.

**Comment by craigbloodworth** [comment]
A valid workaround is to bring it down to v3.4.12
That works just fine

**Comment by vamsisasee** [comment]
Got the same error on 3.6.3 community edition. Seems this has not been fixed as well in the recent edition.

**Comment by jmangue** [comment]
Please feel free to re-assign this one.

**Comment by Xantrul** [comment]
In version 3.0 we updated to the latest available Mongo driver for .NET (2.7.0) and I was able to use MongoDB v4.0.3 Community with LogShark on my local machine.

Closing this, but let us know if you still see issues with the newer versions of Mongo
