### ISSUE TITLE
Not able to successfully run the Logshark 

### ISSUE THREAD

**Issue by aelmoun2** [tableau/Logshark#33]
Hi, 

I am unable to successfully run logshark after following all the steps in the Doc.
When running : 
C:\Program Files\Logshark>logshark C:\Users\Alex\Downloads\mylogs10262017 --startlocalmongo
Loading Logshark user configuration..
Target must be a valid file, directory or MD5 hash!
C:\Program Files\Logshark>

Please see below and let me know if there is anything wrong with my settings:

![image](https://user-images.githubusercontent.com/22208518/34110031-6d04e0bc-e3d3-11e7-913f-9f20f7b8ea20.png)

![image](https://user-images.githubusercontent.com/22208518/34110053-7afccd88-e3d3-11e7-8659-a94e7c175475.png)

Thank you

**Comment by jmangue** [comment]
Hi @aelmoun2 --

How are you generating "mylogs10262017"?  As mentioned in the error, it appears that these logs aren't valid.

Try generating a logset using "tabadmin ziplogs" or the "Generate Log Snapshot" feature in Tableau Server and see if your issue persists... let me know how it goes.

**Comment by aelmoun2** [comment]
Hi @jmangue 

I finally got it resolved, the issue was very simple that the zip file was not displaying the zip extension.
All working fine now as expected.

Thank you for reaching out.

**Comment by jmangue** [comment]
Awesome, thanks for letting me know how it ended up, @aelmoun2 !  Closing this issue out.
