### ISSUE TITLE
Fatal error - 1 is not a supported code page

### ISSUE THREAD

**Issue by Rsini** [tableau/Logshark#37]
Hi.
just installed logshark as described here :https://tableau.github.io/Logshark/docs/logshark_prefunc
when i run logshark i get this:
D:\Program files\Logshark>logshark "d:\logs\11.zip" --startlocalmongo
Loading Logshark user configuration..
Purging existing MongoDB data..
Starting local MongoDB instance on port 27017..
MongoDB started successfully!
Preparing logset target 'd:\logs\hp.zip' for processing..
Encountered a fatal error while extracting logset: 1 is not a supported code page.
Parameter name: codepage
Shutting down local MongoDB process..
Logshark run complete! [00.16]

tried reinstalling everything 
what am i doing wrong?

thanks.

**Comment by Rsini** [comment]
The problem was Format settings in Region (language) settings.
thank you.

**Comment by jmangue** [comment]
Hey @Rsini , glad to hear you figured it out!  Hopefully this helps anyone else who hits the same issue.  Closing this out.
