### ISSUE TITLE
Worbook Names coming up as book1 rather than actual names.

### ISSUE THREAD

**Issue by shazeltion17** [tableau/Logshark#38]
When I look at the logshark workbook for the plugin - vizqlserverperformance.  I try to filter down to the workbook, however i see that almost all of the workbooks are named book1.  It is really weird and I have nothing in the logs that says there is a book1 on my server.

My process was i pointed to tabjolt to my server to run some testing.  I then took a ziplogs, i then ran logshark and I now only see book1 in the workbook.  I have attached that output as an extract so I can share here.

I have also provided the ziplogs for your review.

**Comment by shazeltion17** [comment]
[testlogs.zip](https://github.com/tableau/Logshark/files/1838868/testlogs.zip)

Here they are

**Comment by shazeltion17** [comment]
[testlogs.zip](https://github.com/tableau/Logshark/files/1838920/testlogs.zip)

**Comment by shazeltion17** [comment]
[Book1IssueVizqlServerPerformance.zip](https://github.com/tableau/Logshark/files/1838931/Book1IssueVizqlServerPerformance.zip)

**Comment by jmangue** [comment]
Hi,

"Book1" is a default that Tableau Server often substitutes in for workbook name.  If you search the vizqlserver (directory .\vizqlserver\Logs\) logs in the logset you posted, you can actually see Book1 being logged in many places.  For example:

```{"ts":"2018-03-22T09:51:48.424","pid":3504,"tid":"25c4","sev":"info","req":"WrPfJArUJgYAABFIPJ0AAAIj","sess":"-","site":"Default","user":"sehrlich","k":"create-session","a":{"depth":1,"elapsed":0.002,"end":"2018-03-22T16:51:48.379Z","id":"P/////DxkeJP////+BJev3","name":"create-session","res":{"alloc":{"e":"1.05e+05","i":"1.05e+05","ne":1106,"ni":1106},"free":{"e":"3.13e+04","i":"3.13e+04","ne":383,"ni":383}},"rk":"success","rv":"","sponsor":"P////+TdUBKJ9xLfxnWT6v","type":"end","view":"","workbook":"Book1"},"v":{"sess":"1B337E1CDF0D4A68A8E0CA3F2B82CEFC-0:0","site":"Default","user":"sehrlich",**"workbook":"Book1"**}}```

If you feel that Book1 is not what should be logged, you could look into opening a bug against the Tableau Server product.  But I don't think there is anything actionable here from Logshark's perspective, as it is simply persisting the "workbook" field as-is.

I hope that helps.  If you disagree or see a specific log entry where Logshark is persisting the wrong data, please feel free to reopen this.
