### ISSUE TITLE
Fatal error while extracting logset. There is not enough space on the disk

### ISSUE THREAD

**Issue by jas8209** [tableau/Logshark#39]
Hi,

I am trying to generate log shark workbooks but getting error "Fatal error while extracting logset. There is not enough space on the disk".

**Comment by jmangue** [comment]
Hi @jas8209 , it sounds like the disk hosting your TEMP folder does not have space to extract the logset you're running Logshark on.  Please try freeing up some space and try again.

**Comment by preetjawaria** [comment]
Hi @jmangue , I am facing the same error.
The complete error is as : 
Encountered a fatal error  while extracting logset : Failed to copy target 'C:\Logs' to local temp directory : could not find a part of the path C\Program Files\Logshark\Temp\win-k3rpsh4gn5d_18051011453678\

Even I am having C disk free (almost 66 GB).
Please help.

**Comment by jmangue** [comment]
Hi @preetjawaria, in your log message the path `C\Program Files\Logshark\Temp\win-k3rpsh4gn5d_18051011453678\` is missing a ":" after the volume.  Please double check your TEMP and TMP environment variables to make sure the syntax is correct.

**Comment by jmangue** [comment]
Resolving as inactive; please reopen if you still need help.
