### ISSUE TITLE
Running Logshark in command line 

### ISSUE THREAD

**Issue by simi676** [tableau/Logshark#4]
Hi ,

I recently came across this tool and wanted to get started . I have successfully installed the standalone Postgres instance and trying to run logshark in command line with full admin rights. I  am using this after opening cmd - **C:\"C:\Program Files\Logshark\Logshark.exe"** but this says No logset target specified.

I tried several combinations like  C:\Program Files\Logshark>Logshark C:\Users\User1\Desktop\Tableau Ziplog\UAT Logs.zip -- plugin Apache.

But this doesn't give me any output file. I am sure that I am missing something here but couldn't get it working as I read the User guide.

I will really appreciate if you can help me with this trivial thing.

Thanks!

**Comment by jmangue** [comment]
Hi simi676,

If there are spaces in the path to your logset, you will need to wrap the path with double quotes.  Can you please try executing the following:

**logshark "C:\Users\User1\Desktop\Tableau Ziplog\UAT Logs.zip" --plugins Apache**

Thanks for trying Logshark, let me know how it goes!

**Comment by simi676** [comment]
Thank you  Justin ! It worked like a magic. I will let you know if I face any further problems or need some clarification for understanding. Thanks for this awesome product.

**Comment by jmangue** [comment]
Awesome -- glad to hear it's working for you simi676! 👍 Closing this issue out.
