### ISSUE TITLE
Logshark on AWS

### ISSUE THREAD

**Issue by BFASEricP** [tableau/Logshark#41]
We are looking into installing Logshark in an AWS environment. Do you have any recommendations? We plan on using a RDS for the PostgreSQL database, but it looks like we will have to install MongoDB on a virtual server, right?

**Comment by jmangue** [comment]
Hi @BFASEricP , I don't have any firsthand experience with using Logshark in an AWS environment, but your assumptions sound correct to me... you'll need either MongoDB on an EC2 instance or else you can run one locally using --startlocalmongo.  Let us know how it goes!

**Comment by jmangue** [comment]
Closing this out as answered; please reopen if you have additional questions on this thread.
