### ISSUE TITLE
Logshark not working with Tableau Server 2018.1

### ISSUE THREAD

**Issue by timothyvermeiren** [tableau/Logshark#43]
Since we've upgraded to 2018.1, Logshark has been unable (or rather, "unwilling") to process the log files for our Tableau Server. The error thrown is:

`[2018-05-14T02-20-30] Failed to initialize Logshark: No compatible artifact processor found for payload! Is this a valid logset?`

I've looked into the issue and seem to have found that this is due to the checks being done in TableauServerLogProcessor.cs. This file is, if I'm not mistaken, looking for the buildversion.txt file to confirm that the logs are coming from server. As of 2018.1, it _seems_ like this little guy isn't included in the ziplogs anymore.

And effectively, if I manually copy a buildversion.txt from an older (10.5) zip file into the new one, then run Logshark, it agrees to proceed normally.

After that, it doesn't finish correctly. It seems to get stuck on log files that have lines of over 100K characters. But perhaps it's more suitable to open a different issue for this?

**Comment by jmangue** [comment]
Hi @timothyvermeiren --

Thanks for the report... yeah, the buildversion.txt file was removed in 2018.1, which impacts Logshark.  This is a known issue that will be addressed in the next release.  I am labeling this as a bug and we will update this once the new release is out.

**Comment by timothyvermeiren** [comment]
Thanks for the response @jmangue! Good to hear.

Should I open a separate issue for the >100K line length issue? Or is this something you are aware of already? I don't have much extra information on this yet, but I could obtain it if necessary.

**Comment by jmangue** [comment]
Hey @timothyvermeiren, we just released v2.1 (https://github.com/tableau/Logshark/releases/tag/v2.1) which should resolve the buildversion.txt issue.  If you're still having problems with >100K line length, please go ahead and file an issue... that's a new one to me :smile:
