### ISSUE TITLE
Serialization error with hyper?

### ISSUE THREAD

**Issue by Ewpefrjc** [tableau/Logshark#49]
We have Tableau 10.5.3; and using the new logshark 2.1; are getting an error; but it's not a fatal error; but wondering if we should be worried; or if there is a configuration setting somewhere to change this. 

Failed to process file 'hyper\hyper_2018_06_28_02_56_49-part2.log': Maximum serialization depth exceeded (does the object being serialized have a circular reference?).

Here's the logfile and the config file; stripped of servernames, usernames, and passwords.
[Logshark.config.txt](https://github.com/tableau/Logshark/files/2146913/Logshark.config.txt)
[tableau_logshark.log.20180628.152256.txt](https://github.com/tableau/Logshark/files/2146914/tableau_logshark.log.20180628.152256.txt)

**Comment by Xantrul** [comment]
Hi,
Thanks for reporting this! The problem is caused by the deeply nested json in hyper logs (often occurs when log level is set above INFO). We will fix it in the next release of LogShark

**Comment by Xantrul** [comment]
Version 3.0 able to recognize this scenario and issues a correct warning. We exclude such long lines from results, however they do not affect anything else and the rest of the data should be complete
