### ISSUE TITLE
Cannot process logs with external MongoDB

### ISSUE THREAD

**Issue by thelumlaa** [tableau/Logshark#50]
Hi,

Just configured external mongoDB, the logshark run goes fine till the end and then it shows the following error
Logshark run failed: MongoDB database c1436dec9a9af2ea0380388b37872e26 contains
no valid log data!

Then i re-ran it one more time, it found the hash (was quicker) and here's what it says:

Logshark run complete! [01:07.86]
Logset hash for this run was 'c1436dec9a9af2ea0380388b37872e26'.
Logshark run failed: Unable to determine status of logset. Aborting..

Please share your thoughts on how to fix the issue.
Thanks

**Comment by Xantrul** [comment]
Closing due to the lack of activity in this thread
