### ISSUE TITLE
Publishing to Tableau server 2018.1

### ISSUE THREAD

**Issue by RobPalmer85** [tableau/Logshark#51]
Hello,

When I try to get Logshark v2.1 to publish to Tableau Server 2018.1 I get the following error:

Publishing of workbook 'ClusterController.twb' failed: Failed to publish workbook 'ClusterController.twb': Failed to retrieve successful response for POST request to 'http://xx.xx.xx.xx/api/2.2/sites/0120d718-bef4-4057-b319-96b7b2334a28/workbooks?overwrite=True' after 3 attempts: The remote server returned an error: (403) Forbidden. [3 attempts made]

I've tried this with  Explorer (can publish), site administrator explorer and server administrator permissions and I get the same error. I know the API is enabled as I ensured this was the case this morning.

Any ideas?

Thanks
Rob

**Comment by jmangue** [comment]
Hey Rob,

Hm, sounds like you've checked most of the things I would recommend here (making sure Logshark is using a site admin account, and making sure the REST API is enabled).

The only other thing I can think of to check is whether the server has permission to access the data source in the workbook.  Does your Tableau Server have access to query data from your Logshark Postgres database? Typically this involves editing the pg_hba.conf file.

**Comment by RobPalmer85** [comment]
Hello,

Thanks for the quick response. Unfortunately the server does have access. I've managed to publish the dashboards by copying the output to a dev server and publishing with Tableau desktop. I think it might be related to the server name that's being used in the connection. When doing the workaround I made sure to use IP address instead and that seems to work.

Thanks
Rob

**Comment by Xantrul** [comment]
Hi Rob,
Does it work if you use IP address in Logshark.config as well? If yes - what is the hostname which fails? I saw in the past that some symbols in URLs can make other applications to act weird (i.e. IE doesn't accept any cookies from URLs with dash in them)

**Comment by Xantrul** [comment]
Closing due to the lack of activity in this thread
