### ISSUE TITLE
Error inserting into hyper: Element name 'lower.value' is not valid'.

### ISSUE THREAD

**Issue by EveryoneIsAnotherYou** [tableau/Logshark#52]
I'm seeing errors when the Hyper plug-in does ingestion on Logshark v2.1 with Tableau Server 2018.1.3 on Windows:

**Error inserting into hyper: Element name 'lower.value' is not valid'.**

Should I be concerned about these?

**Comment by Xantrul** [comment]
Hi Grant,
This error in general means that we failed to insert batch of documents into Mongo, and thus they won't be available for Hyper plugin later. So the worst that could happen is - you don't get complete data from Hyper plugin.

I would test this in our internal version (which is slightly ahead of GitHub) and see if it resolved with the recent changes. I'll shoot you an email with details

**Comment by Xantrul** [comment]
This is fixed in version 3.0
