### ISSUE TITLE
Tableau 2018.2 Linux

### ISSUE THREAD

**Issue by gembox** [tableau/Logshark#53]
We moved to Tableau 2018.2 on Linux and it looks like the log structure has changed significantly. Is 2018.2/Linux supported? I get the errors below on all except the Topology and Full Config dashboards.

Initializing VizqlServer plugin..
Execution of VizqlServer plugin started at 12:00 PM..
0/{ItemsExpected} VizqlServerSession items have been persisted to the database. [{PercentComplete}]
Failed to persist any data from Vizqlserver logs!
Skipped saving workbooks for VizqlServer because the plugin did not generate any backing data.

**Comment by Xantrul** [comment]
LogShark can process Linux logs, but current version doesn't support 2018.2 changes yet (both Linux and Windows). Support for 2018.2 should be added with the next release (no estimates on when it happens though)

**Comment by Xantrul** [comment]
Version 3.0 should be able to process 2018.2 logs (both Linux and Windows). Please let us know if you still seeing issues
