### ISSUE TITLE
Logshark 2.1 failed to run VizqlServerPerformance plugin

### ISSUE THREAD

**Issue by hanshu51** [tableau/Logshark#55]
I found it very useful to run the VizqlServerPerformance plugin for more performance info.
To enable VizqlServerPerformance, you had to explicitly enable it in the logshar.config.

After upgrading to logshark 2.1 this fails. Please check the attached partial logfile.

Please advice what to do to resolve this. Or is it a bug?

Top of the logfile, shows 'vizqlServer' is running OK. But 'VizqlServerPerformance' after it does not.
Execution of VizqlServer plugin started at 11:10 AM..
1070/1622 VizqlServerSession items have been persisted to the database. [65%]
1622/1622 VizqlServerSession items have been persisted to the database. [100%]
Saved workbook to 'D:\Program Files\Logshark\Output\itsmon01_18100208585203_wkplogs20180923zip\VizqlServer.twb'!
VizqlServer execution completed! [42.35]
Initializing VizqlServerPerformance plugin..
Execution of VizqlServerPerformance plugin started at 11:11 AM..
Exception processing end-visual-model-producer events on session 0A2F01C8906243BFAF839A8761C71695-0:0: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Logline key not of type end-visual-interpreter!
   at Logshark.Plugins.Vizql.Models.VizqlEvent.ValidateArguments(String expectedKeyType, BsonDocument document)
   at Logshark.Plugins.Vizql.Models.Events.Render.VizqlEndVisualInterpreter..ctor(BsonDocument document)
   --- End of inner exception stack trace ---

[logshark_partial_vizqlserverperformance_fails.txt](https://github.com/tableau/Logshark/files/2480360/logshark_partial_vizqlserverperformance_fails.txt)

**Comment by Xantrul** [comment]
Hi hanshu51,

Please try Logshark v3.0 and let us know if the same exception occurs.

**Comment by hanshu51** [comment]
Yes Evgenii,

VizqlServerPerformance is working again, with Logshark 3.0
Thxs for your help.

Rgds,
Hans.
