### ISSUE TITLE
What dashboard does the SampleScreenShot come from ?

### ISSUE THREAD

**Issue by Fababal** [tableau/Logshark#7]
Hello Guys,

Is the sample screen shot coming from one of the sample dashboards ?

Thansk,
Fab.

**Comment by jmangue** [comment]
Hi Fababal,

Yes -- the sample screenshot is from the workbook output by running the "Apache" plugin.

Let us know if you have any other questions!

**Comment by Fababal** [comment]
Thanks a lot for your work and for your answer.
