### ISSUE TITLE
PostgreSQL and MongoDB maintenance

### ISSUE THREAD

**Issue by BFASEricP** [tableau/Logshark#72]
I have been using Logshark for a while now and have noticed that there are a number of databases in both PostgreSQL and MongoDB from each time I've run it. What would be the proper way to clean these up?

**Comment by Xantrul** [comment]
Hi BFASEricP,

LogShark only purges its own local Mongo database (if used) and old results from its own Output folder upon startup (both configured in Logshark.config file).

We do not delete anything from external databases (both Mongo and PostgreSQL) as we don't have enough information about what is safe to delete and what you would like to keep. So it is up to you how and when to delete old run results.
