### ISSUE TITLE
Logshark using APPDATA folder

### ISSUE THREAD

**Issue by LordNeilLord** [tableau/Logshark#73]
Logshak 3.01 is by default using local appdata folder to unpack files with no option to change. In my scenario C: is a very small OS drive with program files installed on D:

Logshark fails in this instance as there is enough space on C: to complete the process

![tempsnip](https://user-images.githubusercontent.com/28431003/50306534-c267e780-048d-11e9-8ede-e7fef0905238.png)

**Comment by Xantrul** [comment]
Hi LordNeilLord,

In version 3.0.1 you can specify temp folder location in logshark.config. It was supposed to have this option commented-out in config, but I updated wrong config file and it is not visible by default. Still works if you enter correct value manually.

To specify temp folder, just add this record nested under <RunOptions> element in config:
`<TempFolder path="C:\Temp\LogSharkDev" />`

Full example:
```
<RunOptions>
    <DataRetention maxRuns="1" />
    <LocalMongo useAlways="true" purgeOnStartup="false" />
    <Tuning>
      <FilePartitioner concurrencyLimit="4" maxFileSizeMb="250" />
      <FileProcessor concurrencyLimitPerCore="1" />
    </Tuning>
    <TempFolder path="C:\Temp\LogSharkDev" />
</RunOptions>
```
