### ISSUE TITLE
Failed publishing woekbooks to Tableau Server v2018.3.2

### ISSUE THREAD

**Issue by cavernaria** [tableau/Logshark#75]
Hello,

I am using logshark. I can see the workbook on the local PC.
However, it can not be published to Tableau Server.(`-p` option)

This is an error message.

> Publishing 1 workbook to Tableau Server..
> Failed to publish workbooks: Unable to initialize Tableau Server for publishing: Failed to retrieve site ID for site 'default': Failed to retrieve successful response for GET request to 'http://xxxxxxxxxx/api/2.2/sites/default?key=name'

The setting is as follows.

Logshark.config
- User is Server Administrator
- Site is default

Tableau Server
- REST API is enabled.
- It is not SAML.

What is the cause of this error?

**Comment by Xantrul** [comment]
Hi cavernaria,

Plz try to use "Default" for the site name (capital D). Per example here: https://onlinehelp.tableau.com/v9.3/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Query_Site

**Comment by cavernaria** [comment]
I used "Default" (capital D). But the results were the same.
(Same error message)

**Comment by Xantrul** [comment]
afaik, this error message means only one thing - site with this name was not found. Try to double-check what name your default site has on Tableau Server - it could be changed from "Default" to something else.

If site name matches exactly, but you still see the error, try to run REST API request from the error message manually (i.e. with Postman or curl). You can also check Tableau Server's Vizportal logs to see if they contain more detailed error message.

**Comment by cavernaria** [comment]
I confirmed the site ID. It definitely was "Default". Also, I created a separate site, I specified that site and published it, but the same error occurred.

I tried publishing with the REST API. This was successful.

Is there a problem with Logshark publishing logic?

**Comment by cavernaria** [comment]
Just a random thought, but ...

I checked the Vizportal log. The following error was written there.

`ResourceNotFoundRestException: Group not found`

My Tableau Server is in Japanese. The group "All Users" is also in Japanese. However, is not "All Users in English" used in the program?  Can you think of this as the cause?

**Comment by Xantrul** [comment]
Looks like we indeed have All Users group hard-coded in the publishing logic:
`protected const string DefaultProjectPermissionsGroup = "All Users";`
We also don't have any logic to handle the scenario where such group is not found. This is something we need to address in the future.

In the meantime, plz try to create empty "All Users" group directly on Tableau Server and see if it helps.

Also, getting back to the original error message reported - the URL reported as problematic was:
`'http://xxxxxxxxxx/api/2.2/sites/default?key=name'`
If you still see this, plz try to run this particular URL manually. Note that here "default" is the site **name**, not ID. Sometimes they match, and something they don't

**Comment by cavernaria** [comment]
I tried to make a group called "All Users". However, the following error message was displayed.

`Another group named All Users already exists.`

My Tableau Server is Japanese on the surface, but internally has the group "All Users"?

**Comment by Xantrul** [comment]
Sorry for the delay in response... 

It is very possible that server has "All Users" group built-in and this name doesn't change internally for different languages. The only other solution I see until we address this problem in the main version is to change the code and build your own version. As far as I can tell, the change should be as simple as removing last two IFs in `Logshark.Core.Controller.Workbook.WorkbookPublisher.InitializeProject` method (but this will prevent LogShark from allowing permissions for "All Users" group to the new projects).

**Comment by Xantrul** [comment]
LogShark v4.1 was [released](https://github.com/tableau/Logshark/releases/tag/v4.1) today!

By default 4.1 doesn't try to add any permissions to any group, so this issue should be resolved. Ability to add default permissions is still present, but must be explicitly configured through config now ([details](https://tableau.github.io/Logshark/docs/logshark_server#set-permissions-for-workbooks))
