### ISSUE TITLE
Logshark always tries to extract to C drive

### ISSUE THREAD

**Issue by SenseiCAY** [tableau/Logshark#76]
Logshark is installed in the D drive. When I run it, it gives me "not enough free disk space available to unpack logs.zip (52 Gb available, 235 Gb required)."

I have 52 G available in the C drive, but well over 235 in the D drive. How can I get Logshark to unpack into the D drive instead?

**Comment by Xantrul** [comment]
Hi SenseiCAY,

Plz try to specify temp folder on D: drive as described in https://github.com/tableau/Logshark/issues/73

**Comment by SenseiCAY** [comment]
Thank you! That fixed it.
