### ISSUE TITLE
Not able to configure logshark with external Mongodb

### ISSUE THREAD

**Issue by Shruthireddye** [tableau/Logshark#77]
Hi,

I am in the process of configuring Logshark with an external MongoDB. I have edited the Logshark.config as mentioned in the Guide. However, when I tried to run the following, I have been receiving an authentication error.

C:\Program Files\Logshark>logshark D:\Logs\logs.zip
Loading Logshark user configuration..
Failed to open connection to MongoDB database 'XX.XXX.XXX.XXX:27017': Command listDatabases failed: command listDatabases requires authentication.
Logshark run failed: Failed to open connection to MongoDB database 'XX.XXX.XXX.XXX:27017': Command listDatabases failed: command listDatabases requires authentication.
 (IP hidden due to security reasons)

I did mention the credentials but for some reason logshark seems to be not able to read it. Please let me know if am missing anything here. 

Appreciate your help.

Thanks,
Shruthi

**Comment by Xantrul** [comment]
Hi,
FWIW, here's the guide we use to enable authentication on our own internal databases:
https://docs.mongodb.com/manual/tutorial/enable-authentication/

The only two problems I had in the past causing similar errors were:
- Forgot to include "--auth" into Mongo startup command
- Did not have "admin" database

**Comment by Xantrul** [comment]
[LogShark v4.1](https://github.com/tableau/Logshark/releases/tag/v4.1) is now the current version and it doesn't use MongoDB anymore. It is MUCH faster than the previous version as well, so please give it a try. In the meantime I am going to close this issue as it is no longer relevant to the current version.
