### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by yapnel** [tableau/Logshark#78]
Wondering it is possible to ingest data into logshark near real time for monitoring and alerting?

**Comment by Xantrul** [comment]
Hi,
This is not the use case Logshark was designed for, so ingesting ongoing data would not be feasible without major rework of the tool.

There are many third-party tools available to ingest and analyze logs at near real time (Splunk, SumoLogic to name the few) and it should be possible to implement some of the logic we use to aggregate/analyze logs in Logshark in these tools as well.
