### ISSUE TITLE
Issues creating Replayer JSON file using Tableau v10.1.1 ziplogs and LogShark v3.0.1

### ISSUE THREAD

**Issue by TonnesOFun** [tableau/Logshark#80]
Hi there,

We are upgrading our Tableau VM from v10.1.1 to v2018.3.3 and wish to do some performance testing.  I am using the logs from Tableau v10.1.1 and running LogShark v3.0.1, with the following command:

logshark C:\Admin\logs\Logs_030419.zip --startlocalmongo --plugins ReplayCreation

I get the following error that I haven't seen before:

C:\Users\jholling>logshark C:\Admin\logs\Logs_030419.zip --startlocalmongo --plugins ReplayCreation
Loading Logshark user configuration..
A MongoDB process is already running.  Attempting to shut it down..
Purging existing MongoDB data..
Starting local MongoDB instance on port 27017..
MongoDB started successfully!
Preparing logset target 'C:\Admin\logs\Logs_030419.zip' for processing..
Extracting contents of archive 'Logs_030419.zip' to 'C:\Users\jholling\AppData\Local\Temp\Logshark\19040413465583'.. (656.5Mb)
Extracted 464 files from 'Logs_030419.zip'. (10.8Gb unpacked)
Finished extracting required files from logset! Unpacked 11Gb out of 657Mb. [01:16.15]
Loaded 3 artifact processors: DesktopLogProcessor, ServerClassicLogProcessor, ServerTsmLogProcessor
Found matching artifact processor: ServerClassicLogProcessor
Computing logset hash..
Logset hash is '99f877ce9b726d908de3be06ef9de297'.
Loaded requested Logshark plugin: ReplayCreation
Found existing logset matching hash! Skipping extraction and parsing.
Initializing ReplayCreation plugin..
Execution of ReplayCreation plugin started at 1:48 PM..
Executing default 5 concurrent queries to get browser sessions
No path specified for Replay json file, it will be saved to default directory - C:\Program Files\Logshark\Output\tts-kirkby060_19040412465431_logs030419zip
No file name specified for Replay json file, the replay file will be saved as - Playback_04_04_-13-48-13.json
Executing ReplayCreation plugin
Querying Access logs for GET requests
Number of Query Results : 237480
Encountered uncaught exception while executing plugin 'ReplayCreation': Input string was not in a correct format.
ReplayCreation failed to execute successfully.
Finished executing plugins! [1 failure]
Logshark run complete! [01:26.04]
Logset hash for this run was '99f877ce9b726d908de3be06ef9de297'.

It worked a few months ago using the same setup so, not sure why it isn't working.

Also, we run a cleanup routine that exports a weeks worth of ziplogs to a network location and when we try to use these logs we get the following error:

C:\Users\jholling>logshark C:\Admin\logs\Logs_310319.zip --startlocalmongo --plugins ReplayCreation
Loading Logshark user configuration..
A MongoDB process is already running.  Attempting to shut it down..
Purging existing MongoDB data..
Starting local MongoDB instance on port 27017..
MongoDB started successfully!
Preparing logset target 'C:\Admin\logs\Logs_310319.zip' for processing..
Extracting contents of archive 'Logs_310319.zip' to 'C:\Users\jholling\AppData\Local\Temp\Logshark\19040414250630'.. (2.2Gb)
Extracting nested archive 'remote_logs.zip' from 'Logs_310319.zip'.. (1039.8Mb)
Extracting nested archive 'inprogress_remote_logs.zip' from 'remote_logs.zip'.. (9.5Mb)
Extracted 9 files from 'inprogress_remote_logs.zip'. (45.4Mb unpacked)
Extracted 599 files from 'remote_logs.zip'. (17Gb unpacked)
Extracted 1324 files from 'Logs_310319.zip'. (36.6Gb unpacked)
Finished extracting required files from logset! Unpacked 37Gb out of 2Gb. [05:01.51]
Loaded 3 artifact processors: DesktopLogProcessor, ServerClassicLogProcessor, ServerTsmLogProcessor
Logshark run complete! [05:04.11]
Logshark run failed: No compatible artifact processor found for payload! Is this a valid logset?

If someone could I would be most appreciative.

Many thanks,

**Comment by UmapathiM001** [comment]
hi,
there are two different issues you have posted here, 
for the first >>"Encountered uncaught exception while executing plugin 'ReplayCreation': Input string was not in a correct format."
I have not seen this issue before, can you look at \Logs\Plugin.ReplayCreation.log.txt for more details on where the issue is reported?

**Comment by Xantrul** [comment]
Hi,
For the second issue - `No compatible artifact processor found for payload! Is this a valid logset?`, it looks like you were trying to process a zip file with multiple log sets inside ('inprogress_remote_logs.zip', 'remote_logs.zip', etc.)

LogShark checks the structure inside the zip file to understand what version it is dealing with and expects to see a one of the known log output formats of Tableau Server. For Tableau Server 10.1 this would be separate folders for each component in the root of the zip (i.e. `/backgrounder/*`,  `/config/*`, etc.). If you have multiple log sets to process - plz process them separately.

**Comment by TonnesOFun** [comment]
@UmapathiM001 - This is an extract from the Plugin.ReplayCreation.log.txt file:
2019-04-04 13:48:13,197 tts-kirkby060_19040412465431_logs030419zip (null) [1] INFO Logshark.Plugins.ReplayCreation.ReplayCreation - Executing default 5 concurrent queries to get browser sessions
2019-04-04 13:48:13,203 tts-kirkby060_19040412465431_logs030419zip (null) [1] INFO Logshark.Plugins.ReplayCreation.ReplayCreation - No path specified for Replay json file, it will be saved to default directory - C:\Program Files\Logshark\Output\tts-kirkby060_19040412465431_logs030419zip
2019-04-04 13:48:13,208 tts-kirkby060_19040412465431_logs030419zip (null) [1] INFO Logshark.Plugins.ReplayCreation.ReplayCreation - No file name specified for Replay json file, the replay file will be saved as - Playback_04_04_-13-48-13.json
2019-04-04 13:48:13,212 tts-kirkby060_19040412465431_logs030419zip (null) [1] INFO Logshark.Plugins.ReplayCreation.ReplayCreation - Executing ReplayCreation plugin
2019-04-04 13:48:13,218 tts-kirkby060_19040412465431_logs030419zip (null) [1] INFO Logshark.Plugins.ReplayCreation.ReplayCreation - Querying Access logs for GET requests
2019-04-04 13:48:20,490 tts-kirkby060_19040412465431_logs030419zip (null) [1] INFO Logshark.Plugins.ReplayCreation.ReplayCreation - Number of Query Results : 237480

**Comment by TonnesOFun** [comment]
@Xantrul Thanks for this, will have a look and separate as advised.

Many thanks,

**Comment by TonnesOFun** [comment]
@Xantrul I've had a look inside the ziplogs file and can confirm that there is only one folder for each component.  However, we have four backgrounders and a log file for each one.

**Comment by TonnesOFun** [comment]
@UmapathiM001 @Xantrul  - I have solved the above issues by running logshark on the development server which has 48GB of vRAM.  I now have a JSON file to use with replay.

Thanks for your help guys.
