### ISSUE TITLE
Feature Request: MongoDB bind to localhost

### ISSUE THREAD

**Issue by slewt** [tableau/Logshark#81]
It would be nice to have mongod included in the application to bind to only the localhost instead of all IPs for this type of use.
Possible implementations. 

- Give a cli option (--bind_ip) to pass to mongod.exe
- Give a cli option to use a config file and include the current defaults in the config file
- Upgrade mongo to v3.6 and leave the default - which appears to be bind to localhost only (https://jira.mongodb.org/browse/SERVER-28229)

Edited to add an obvious one that I hadn't included: The client caller will have to change also to accommodate any of the above 3 server changes

**Comment by javanic** [comment]
Hi Slewt,

In our next update to LogShark we are removing Mongo from the application; it won't be used anymore and it allows LogShark to process logs significantly faster.

**Comment by slewt** [comment]
Sounds good. Thanks
