### ISSUE TITLE
Not replacing data source in Custom Workbook

### ISSUE THREAD

**Issue by barmst02** [tableau/Logshark#83]
I've configured Logshark to run the Apache and CustomWorkbook plugins, configured CustomWorkbookConfig.xml to point to a custom workbook file and indicate an Apache plugin dependency. 
In the logs, I see Logshark process Apache and replace the data source in the default Apache workbook, then I see it process the Custom Workbook but it doesn't replace the data source. I've attached the appropriate log snippet. 
Here is the CustomWorkbookConfig.xml contents:
`<CustomWorkbooks>
  <Workbook name="Performance Metrics.twbx">
    <PluginDependency name="Apache" />
  </Workbook>
</CustomWorkbooks>
`

[Log Snippet.txt](https://github.com/tableau/Logshark/files/3397716/Log.Snippet.txt)

**Comment by javanic** [comment]
Hi barmst02, thanks for using Logshark and letting us know of a problem with the current released version. Normally we'd jump on this and see what needs to be fixed, but we are wrapping up our work on LogShark v4 and it has a redesigned and simpler method of using custom workbooks. Hope you can wait a bit longer for that release.

**Comment by Xantrul** [comment]
LogShark v4.1 was [released](https://github.com/tableau/Logshark/releases/tag/v4.1) today!

Using custom workbooks is much easier now - LogShark will use any provided workbook as long extract name(s) inside twbx file match extract names generated by LogShark. See [documentation](https://tableau.github.io/Logshark/docs/logshark_configure#including-your-own-custom-workbooks) for details
