### ISSUE TITLE
Publish to Nested Project

### ISSUE THREAD

**Issue by yapnel** [tableau/Logshark#84]
Hi

Is there a way to publish the workbooks and hypers into a sub Project?

Thanks

Nelson

**Comment by Xantrul** [comment]
Hi Nelson,

Not at the moment, but this is a great idea! I will add a feature request to our backlog.

**Comment by Xantrul** [comment]
LogShark v4.1 was [released](https://github.com/tableau/Logshark/releases/tag/v4.1) today! This capability is included and can be set up through config. See options under "TableauServer:ParentProject" config section: you can either specify a project name (if it is unique on the site) or project id (you might have to use REST API to get it) if there is more than one project with the same name on the site.
If both parameters are blank (default) - LogShark will create project at the root of the site
