### ISSUE TITLE
Option to Publishing to Different Tableau Server

### ISSUE THREAD

**Issue by yapnel** [tableau/Logshark#85]
Hi

At the moment, one can only publish to a Tableau server defined in the config. It will be good to have the ability to define several servers in the config and in command line specifying which env to publish to. This is handy when dealing with Prod, Test and Dev logs and want to publish to the corresponding servers in a script. It is not possible to achieve now.

Thanks

Nelson

**Comment by Xantrul** [comment]
In LogShark v4 you still have an option to specify Tableau Server details in the config, but also there is an option to override url/site/username/password through the command line parameters. Sounds like this should address use case above. Plz lmk if it is not.

So we just need to wait until v4 release :)

**Comment by yapnel** [comment]
Hi Xantrul,

Is there a rough timeline for v4? Really looking forward to it since it will resolves all my issues.

Thanks again

Nelson

**Comment by javanic** [comment]
Hi yapnel,

For a rough timeline, we will be releasing LogShark v4.0 between late September and early November, 2019. We are taking a dependency on a new Hyper API that will be publicly released, and our wait right now is on the official release of that API.

**Comment by Xantrul** [comment]
LogShark v4.1 was [released](https://github.com/tableau/Logshark/releases/tag/v4.1) today!

It allows to pass many configuration values through command line parameters. See [here](https://tableau.github.io/Logshark/docs/logshark_cmds) for all available command line parameters
