### ISSUE TITLE
Credential Encryption

### ISSUE THREAD

**Issue by yapnel** [tableau/Logshark#86]
Hi,

Is it possible to encrypt the credentials in the config file. Leaving it in clear text form is not secure.

Thanks

Nelson

**Comment by Xantrul** [comment]
This will be addressed in v4 by the same change I mentioned in #85 - since one can specify password through command line parameter now, it is up to the user how they store/obtain value for the parameter.

**Comment by Xantrul** [comment]
LogShark v4.1 was [released](https://github.com/tableau/Logshark/releases/tag/v4.1) today!

It allows to pass secrets like database or Tableau Server credentials through command line parameters. See [here](https://tableau.github.io/Logshark/docs/logshark_cmds) for all available command line parameters
