### ISSUE TITLE
Combined workbooks

### ISSUE THREAD

**Issue by yapnel** [tableau/Logshark#87]
Hi

Is there a way to combine all the workbooks into a single packaged workbook with hypers for publishing?

Thanks

Nelson

**Comment by Xantrul** [comment]
This should be fairly easy to do in v4 as it accepts any workbooks as long as extract name(s) match the output. So you can simply copy-paste sheets/dashboards from all workbooks into one and use that one as a template.

**Comment by Xantrul** [comment]
LogShark v4.1 was released today: https://github.com/tableau/Logshark/releases/tag/v4.1

As I mentioned above, it should be fairly easy to merge workbooks now - just make sure that extract names in the new workbook match extract names generated by LogShark. See [here](https://tableau.github.io/Logshark/docs/logshark_configure.html#including-your-own-custom-workbooks) for more details.
