### ISSUE TITLE
Resource Manager Plugin misisng in Tableau 9.x versions

### ISSUE THREAD

**Issue by poornimasujith** [tableau/Logshark#9]
I am not able to see Resource Manager plugins in the Logshark Output folder of Tableau 9.x versions and I can see it in 10.x versions.
 I am using the normal "tabadmin ziplogs file.zip" command in both 9.x and 10.x versions. Is there any additional switch we need to use in order to generate Resource Manager Plugin output in 9.x version?

Thank you

**Comment by jmangue** [comment]
Hi,

When you say 9.x, what specific versions are you referring to?

The Server Resource Manager did not log out sample data until 9.2, so if you are running Logshark on a 9.0.x or 9.1.x logset then you will not get output.

**Comment by poornimasujith** [comment]
Thank you for the response, I was trying with the version 9.0.x.

Can you provide some documentation on logshark with some use cases of tableau performance issues and how logshark helped to analyze the process which was creating issues. 

Thank you

**Comment by jmangue** [comment]
Poornima,

Unfortunately I don't have any documentation like that that I can give out publicly.

Russell Christopher's blog has a great post about using Logshark to analyze query performance -- see [tableaulove.com](https://tableaulove.com/road-rules-tableau-redshift-part-2-logging/)
